#pragma once

// Generated canonical contract include for the xpu backend.
// Native optimized APIs remain backend-owned behind this adapter surface.

#include "quixicore/contract/kernel_abi.hpp"
#include "quixicore/contract/operations.hpp"
#include "quixicore/xpu/contract_stubs.hpp"

namespace quixicore::xpu::contract_api {

[[nodiscard]] inline quixicore::contract::Status dispatch(
    quixicore::contract::OperationId operation,
    const quixicore::contract::KernelCall& call) noexcept {
  switch (operation) {
    case quixicore::contract::OperationId::accumulate:
      return quixicore::xpu::contract_stubs::accumulate(call);
    case quixicore::contract::OperationId::adamw_masked:
      return quixicore::xpu::contract_stubs::adamw_masked(call);
    case quixicore::contract::OperationId::adaptive_norm_modulation:
      return quixicore::xpu::contract_stubs::adaptive_norm_modulation(call);
    case quixicore::contract::OperationId::adaptive_norm_modulation_qkv:
      return quixicore::xpu::contract_stubs::adaptive_norm_modulation_qkv(call);
    case quixicore::contract::OperationId::adaptive_rms_norm_modulation:
      return quixicore::xpu::contract_stubs::adaptive_rms_norm_modulation(call);
    case quixicore::contract::OperationId::adaptive_rms_norm_modulation_qkv:
      return quixicore::xpu::contract_stubs::adaptive_rms_norm_modulation_qkv(call);
    case quixicore::contract::OperationId::add_id:
      return quixicore::xpu::contract_stubs::add_id(call);
    case quixicore::contract::OperationId::add_relative_position_2d:
      return quixicore::xpu::contract_stubs::add_relative_position_2d(call);
    case quixicore::contract::OperationId::add_scalar:
      return quixicore::xpu::contract_stubs::add_scalar(call);
    case quixicore::contract::OperationId::all_gather_gemm:
      return quixicore::xpu::contract_stubs::all_gather_gemm(call);
    case quixicore::contract::OperationId::all_reduce_rms_norm:
      return quixicore::xpu::contract_stubs::all_reduce_rms_norm(call);
    case quixicore::contract::OperationId::arange:
      return quixicore::xpu::contract_stubs::arange(call);
    case quixicore::contract::OperationId::argsort:
      return quixicore::xpu::contract_stubs::argsort(call);
    case quixicore::contract::OperationId::attention_backward:
      return quixicore::xpu::contract_stubs::attention_backward(call);
    case quixicore::contract::OperationId::attention_gate_residual:
      return quixicore::xpu::contract_stubs::attention_gate_residual(call);
    case quixicore::contract::OperationId::attention_with_lse:
      return quixicore::xpu::contract_stubs::attention_with_lse(call);
    case quixicore::contract::OperationId::audio_causal_depthwise_conv1d:
      return quixicore::xpu::contract_stubs::audio_causal_depthwise_conv1d(call);
    case quixicore::contract::OperationId::audio_conv1d:
      return quixicore::xpu::contract_stubs::audio_conv1d(call);
    case quixicore::contract::OperationId::audio_conv1d_direct:
      return quixicore::xpu::contract_stubs::audio_conv1d_direct(call);
    case quixicore::contract::OperationId::audio_depthwise_conv1d:
      return quixicore::xpu::contract_stubs::audio_depthwise_conv1d(call);
    case quixicore::contract::OperationId::audio_relative_attention:
      return quixicore::xpu::contract_stubs::audio_relative_attention(call);
    case quixicore::contract::OperationId::audio_resample:
      return quixicore::xpu::contract_stubs::audio_resample(call);
    case quixicore::contract::OperationId::avg_pool2d_tokens:
      return quixicore::xpu::contract_stubs::avg_pool2d_tokens(call);
    case quixicore::contract::OperationId::base_q_dequant:
      return quixicore::xpu::contract_stubs::base_q_dequant(call);
    case quixicore::contract::OperationId::base_q_embedding:
      return quixicore::xpu::contract_stubs::base_q_embedding(call);
    case quixicore::contract::OperationId::base_q_gemm:
      return quixicore::xpu::contract_stubs::base_q_gemm(call);
    case quixicore::contract::OperationId::base_q_gemv:
      return quixicore::xpu::contract_stubs::base_q_gemv(call);
    case quixicore::contract::OperationId::base_q_lm_head_argmax:
      return quixicore::xpu::contract_stubs::base_q_lm_head_argmax(call);
    case quixicore::contract::OperationId::base_q_moe_gemm:
      return quixicore::xpu::contract_stubs::base_q_moe_gemm(call);
    case quixicore::contract::OperationId::base_q_moe_swiglu:
      return quixicore::xpu::contract_stubs::base_q_moe_swiglu(call);
    case quixicore::contract::OperationId::base_q_qkv:
      return quixicore::xpu::contract_stubs::base_q_qkv(call);
    case quixicore::contract::OperationId::base_q_swiglu:
      return quixicore::xpu::contract_stubs::base_q_swiglu(call);
    case quixicore::contract::OperationId::based_attention:
      return quixicore::xpu::contract_stubs::based_attention(call);
    case quixicore::contract::OperationId::biased_attention:
      return quixicore::xpu::contract_stubs::biased_attention(call);
    case quixicore::contract::OperationId::broadcast:
      return quixicore::xpu::contract_stubs::broadcast(call);
    case quixicore::contract::OperationId::calibration_absmax:
      return quixicore::xpu::contract_stubs::calibration_absmax(call);
    case quixicore::contract::OperationId::causal_conv3d_cache_update:
      return quixicore::xpu::contract_stubs::causal_conv3d_cache_update(call);
    case quixicore::contract::OperationId::causal_conv_gate_residual:
      return quixicore::xpu::contract_stubs::causal_conv_gate_residual(call);
    case quixicore::contract::OperationId::clamp:
      return quixicore::xpu::contract_stubs::clamp(call);
    case quixicore::contract::OperationId::classifier_free_guidance_combine:
      return quixicore::xpu::contract_stubs::classifier_free_guidance_combine(call);
    case quixicore::contract::OperationId::classifier_free_guidance_scheduler_step:
      return quixicore::xpu::contract_stubs::classifier_free_guidance_scheduler_step(call);
    case quixicore::contract::OperationId::col2im_1d:
      return quixicore::xpu::contract_stubs::col2im_1d(call);
    case quixicore::contract::OperationId::col2im_2d:
      return quixicore::xpu::contract_stubs::col2im_2d(call);
    case quixicore::contract::OperationId::complex_gemm:
      return quixicore::xpu::contract_stubs::complex_gemm(call);
    case quixicore::contract::OperationId::concat:
      return quixicore::xpu::contract_stubs::concat(call);
    case quixicore::contract::OperationId::conv2d:
      return quixicore::xpu::contract_stubs::conv2d(call);
    case quixicore::contract::OperationId::conv3d:
      return quixicore::xpu::contract_stubs::conv3d(call);
    case quixicore::contract::OperationId::conv_transpose_1d:
      return quixicore::xpu::contract_stubs::conv_transpose_1d(call);
    case quixicore::contract::OperationId::conv_transpose_2d:
      return quixicore::xpu::contract_stubs::conv_transpose_2d(call);
    case quixicore::contract::OperationId::conv_transpose_overlap_add:
      return quixicore::xpu::contract_stubs::conv_transpose_overlap_add(call);
    case quixicore::contract::OperationId::cosine:
      return quixicore::xpu::contract_stubs::cosine(call);
    case quixicore::contract::OperationId::count_equal:
      return quixicore::xpu::contract_stubs::count_equal(call);
    case quixicore::contract::OperationId::cross_attention:
      return quixicore::xpu::contract_stubs::cross_attention(call);
    case quixicore::contract::OperationId::cross_entropy_backward:
      return quixicore::xpu::contract_stubs::cross_entropy_backward(call);
    case quixicore::contract::OperationId::ctc_decode:
      return quixicore::xpu::contract_stubs::ctc_decode(call);
    case quixicore::contract::OperationId::cumulative_sum:
      return quixicore::xpu::contract_stubs::cumulative_sum(call);
    case quixicore::contract::OperationId::decode_cache_attention:
      return quixicore::xpu::contract_stubs::decode_cache_attention(call);
    case quixicore::contract::OperationId::decode_linear:
      return quixicore::xpu::contract_stubs::decode_linear(call);
    case quixicore::contract::OperationId::decode_linear_q8:
      return quixicore::xpu::contract_stubs::decode_linear_q8(call);
    case quixicore::contract::OperationId::decode_linear_residual:
      return quixicore::xpu::contract_stubs::decode_linear_residual(call);
    case quixicore::contract::OperationId::decode_swiglu:
      return quixicore::xpu::contract_stubs::decode_swiglu(call);
    case quixicore::contract::OperationId::deformable_attention:
      return quixicore::xpu::contract_stubs::deformable_attention(call);
    case quixicore::contract::OperationId::dense_gemm_ex:
      return quixicore::xpu::contract_stubs::dense_gemm_ex(call);
    case quixicore::contract::OperationId::depthwise_conv2d:
      return quixicore::xpu::contract_stubs::depthwise_conv2d(call);
    case quixicore::contract::OperationId::dequant_gather:
      return quixicore::xpu::contract_stubs::dequant_gather(call);
    case quixicore::contract::OperationId::deterministic_noise:
      return quixicore::xpu::contract_stubs::deterministic_noise(call);
    case quixicore::contract::OperationId::diag_embed:
      return quixicore::xpu::contract_stubs::diag_embed(call);
    case quixicore::contract::OperationId::diag_mask:
      return quixicore::xpu::contract_stubs::diag_mask(call);
    case quixicore::contract::OperationId::diffusion_scheduler_step:
      return quixicore::xpu::contract_stubs::diffusion_scheduler_step(call);
    case quixicore::contract::OperationId::divide:
      return quixicore::xpu::contract_stubs::divide(call);
    case quixicore::contract::OperationId::down_projection_residual:
      return quixicore::xpu::contract_stubs::down_projection_residual(call);
    case quixicore::contract::OperationId::downsample_3d:
      return quixicore::xpu::contract_stubs::downsample_3d(call);
    case quixicore::contract::OperationId::downsample_conv2d:
      return quixicore::xpu::contract_stubs::downsample_conv2d(call);
    case quixicore::contract::OperationId::dsv4_hc_comb:
      return quixicore::xpu::contract_stubs::dsv4_hc_comb(call);
    case quixicore::contract::OperationId::dsv4_hc_post:
      return quixicore::xpu::contract_stubs::dsv4_hc_post(call);
    case quixicore::contract::OperationId::dsv4_hc_pre:
      return quixicore::xpu::contract_stubs::dsv4_hc_pre(call);
    case quixicore::contract::OperationId::edge_mlp_256x7:
      return quixicore::xpu::contract_stubs::edge_mlp_256x7(call);
    case quixicore::contract::OperationId::embedding_backward:
      return quixicore::xpu::contract_stubs::embedding_backward(call);
    case quixicore::contract::OperationId::embedding_lookup_types:
      return quixicore::xpu::contract_stubs::embedding_lookup_types(call);
    case quixicore::contract::OperationId::extract_patches_2d:
      return quixicore::xpu::contract_stubs::extract_patches_2d(call);
    case quixicore::contract::OperationId::extract_patches_3d:
      return quixicore::xpu::contract_stubs::extract_patches_3d(call);
    case quixicore::contract::OperationId::factorized_position_2d:
      return quixicore::xpu::contract_stubs::factorized_position_2d(call);
    case quixicore::contract::OperationId::fake_quant_float8:
      return quixicore::xpu::contract_stubs::fake_quant_float8(call);
    case quixicore::contract::OperationId::fake_quant_int8:
      return quixicore::xpu::contract_stubs::fake_quant_int8(call);
    case quixicore::contract::OperationId::fft_convolution:
      return quixicore::xpu::contract_stubs::fft_convolution(call);
    case quixicore::contract::OperationId::fill:
      return quixicore::xpu::contract_stubs::fill(call);
    case quixicore::contract::OperationId::flow_euler_step:
      return quixicore::xpu::contract_stubs::flow_euler_step(call);
    case quixicore::contract::OperationId::flow_step_action_clamp_denormalize:
      return quixicore::xpu::contract_stubs::flow_step_action_clamp_denormalize(call);
    case quixicore::contract::OperationId::fp8_gemm:
      return quixicore::xpu::contract_stubs::fp8_gemm(call);
    case quixicore::contract::OperationId::fp8_scaled_gemm:
      return quixicore::xpu::contract_stubs::fp8_scaled_gemm(call);
    case quixicore::contract::OperationId::gate_up_projection_swiglu:
      return quixicore::xpu::contract_stubs::gate_up_projection_swiglu(call);
    case quixicore::contract::OperationId::gated_linear_attention:
      return quixicore::xpu::contract_stubs::gated_linear_attention(call);
    case quixicore::contract::OperationId::gdn_gate_beta:
      return quixicore::xpu::contract_stubs::gdn_gate_beta(call);
    case quixicore::contract::OperationId::gdn_gated_rmsnorm:
      return quixicore::xpu::contract_stubs::gdn_gated_rmsnorm(call);
    case quixicore::contract::OperationId::gdn_qkv_prepare:
      return quixicore::xpu::contract_stubs::gdn_qkv_prepare(call);
    case quixicore::contract::OperationId::gdn_recurrence:
      return quixicore::xpu::contract_stubs::gdn_recurrence(call);
    case quixicore::contract::OperationId::gdn_short_conv:
      return quixicore::xpu::contract_stubs::gdn_short_conv(call);
    case quixicore::contract::OperationId::geglu_projection:
      return quixicore::xpu::contract_stubs::geglu_projection(call);
    case quixicore::contract::OperationId::gemm_gate_residual:
      return quixicore::xpu::contract_stubs::gemm_gate_residual(call);
    case quixicore::contract::OperationId::get_relative_position:
      return quixicore::xpu::contract_stubs::get_relative_position(call);
    case quixicore::contract::OperationId::grammar_mask:
      return quixicore::xpu::contract_stubs::grammar_mask(call);
    case quixicore::contract::OperationId::grid_sample:
      return quixicore::xpu::contract_stubs::grid_sample(call);
    case quixicore::contract::OperationId::group_norm:
      return quixicore::xpu::contract_stubs::group_norm(call);
    case quixicore::contract::OperationId::group_norm_silu:
      return quixicore::xpu::contract_stubs::group_norm_silu(call);
    case quixicore::contract::OperationId::grouped_gemm:
      return quixicore::xpu::contract_stubs::grouped_gemm(call);
    case quixicore::contract::OperationId::hedgehog_attention:
      return quixicore::xpu::contract_stubs::hedgehog_attention(call);
    case quixicore::contract::OperationId::im2col_2d:
      return quixicore::xpu::contract_stubs::im2col_2d(call);
    case quixicore::contract::OperationId::im2col_3d:
      return quixicore::xpu::contract_stubs::im2col_3d(call);
    case quixicore::contract::OperationId::indexer_k_gather:
      return quixicore::xpu::contract_stubs::indexer_k_gather(call);
    case quixicore::contract::OperationId::interpolate_position_2d:
      return quixicore::xpu::contract_stubs::interpolate_position_2d(call);
    case quixicore::contract::OperationId::istft:
      return quixicore::xpu::contract_stubs::istft(call);
    case quixicore::contract::OperationId::joint_multimodal_attention:
      return quixicore::xpu::contract_stubs::joint_multimodal_attention(call);
    case quixicore::contract::OperationId::kd_ce_fused_bwd:
      return quixicore::xpu::contract_stubs::kd_ce_fused_bwd(call);
    case quixicore::contract::OperationId::kd_ce_fused_fwd:
      return quixicore::xpu::contract_stubs::kd_ce_fused_fwd(call);
    case quixicore::contract::OperationId::kd_kl_dense_bwd:
      return quixicore::xpu::contract_stubs::kd_kl_dense_bwd(call);
    case quixicore::contract::OperationId::kd_kl_dense_fwd:
      return quixicore::xpu::contract_stubs::kd_kl_dense_fwd(call);
    case quixicore::contract::OperationId::kd_kl_topk_bwd:
      return quixicore::xpu::contract_stubs::kd_kl_topk_bwd(call);
    case quixicore::contract::OperationId::kd_kl_topk_fwd:
      return quixicore::xpu::contract_stubs::kd_kl_topk_fwd(call);
    case quixicore::contract::OperationId::kv_cache_compact:
      return quixicore::xpu::contract_stubs::kv_cache_compact(call);
    case quixicore::contract::OperationId::kv_cache_copy_blocks_q8_0:
      return quixicore::xpu::contract_stubs::kv_cache_copy_blocks_q8_0(call);
    case quixicore::contract::OperationId::kv_cache_gather_bitnet_kv3:
      return quixicore::xpu::contract_stubs::kv_cache_gather_bitnet_kv3(call);
    case quixicore::contract::OperationId::kv_cache_gather_q8_0:
      return quixicore::xpu::contract_stubs::kv_cache_gather_q8_0(call);
    case quixicore::contract::OperationId::kv_cache_offload:
      return quixicore::xpu::contract_stubs::kv_cache_offload(call);
    case quixicore::contract::OperationId::kv_cache_scatter_bitnet_kv3:
      return quixicore::xpu::contract_stubs::kv_cache_scatter_bitnet_kv3(call);
    case quixicore::contract::OperationId::kv_cache_scatter_q8_0:
      return quixicore::xpu::contract_stubs::kv_cache_scatter_q8_0(call);
    case quixicore::contract::OperationId::l2_normalize:
      return quixicore::xpu::contract_stubs::l2_normalize(call);
    case quixicore::contract::OperationId::leaky_relu:
      return quixicore::xpu::contract_stubs::leaky_relu(call);
    case quixicore::contract::OperationId::linear_attention_unnormalized:
      return quixicore::xpu::contract_stubs::linear_attention_unnormalized(call);
    case quixicore::contract::OperationId::linear_epilogue:
      return quixicore::xpu::contract_stubs::linear_epilogue(call);
    case quixicore::contract::OperationId::lm_head_beam_advance:
      return quixicore::xpu::contract_stubs::lm_head_beam_advance(call);
    case quixicore::contract::OperationId::lm_head_candidates:
      return quixicore::xpu::contract_stubs::lm_head_candidates(call);
    case quixicore::contract::OperationId::lm_head_masked:
      return quixicore::xpu::contract_stubs::lm_head_masked(call);
    case quixicore::contract::OperationId::log_mel_spectrogram:
      return quixicore::xpu::contract_stubs::log_mel_spectrogram(call);
    case quixicore::contract::OperationId::logarithm:
      return quixicore::xpu::contract_stubs::logarithm(call);
    case quixicore::contract::OperationId::logits_bias_penalties_top_k_top_p_sample:
      return quixicore::xpu::contract_stubs::logits_bias_penalties_top_k_top_p_sample(call);
    case quixicore::contract::OperationId::logits_softcap:
      return quixicore::xpu::contract_stubs::logits_softcap(call);
    case quixicore::contract::OperationId::lora_apply:
      return quixicore::xpu::contract_stubs::lora_apply(call);
    case quixicore::contract::OperationId::lora_apply_direct_f16:
      return quixicore::xpu::contract_stubs::lora_apply_direct_f16(call);
    case quixicore::contract::OperationId::mamba2_backward:
      return quixicore::xpu::contract_stubs::mamba2_backward(call);
    case quixicore::contract::OperationId::masked_mean_pool_rms_l2:
      return quixicore::xpu::contract_stubs::masked_mean_pool_rms_l2(call);
    case quixicore::contract::OperationId::mean_pool_rms_l2:
      return quixicore::xpu::contract_stubs::mean_pool_rms_l2(call);
    case quixicore::contract::OperationId::mixed_prefill_decode_attention:
      return quixicore::xpu::contract_stubs::mixed_prefill_decode_attention(call);
    case quixicore::contract::OperationId::moe_all_to_all_dispatch:
      return quixicore::xpu::contract_stubs::moe_all_to_all_dispatch(call);
    case quixicore::contract::OperationId::moe_finalize_backward:
      return quixicore::xpu::contract_stubs::moe_finalize_backward(call);
    case quixicore::contract::OperationId::moe_gather_backward:
      return quixicore::xpu::contract_stubs::moe_gather_backward(call);
    case quixicore::contract::OperationId::moe_grouped_gemm_backward_input:
      return quixicore::xpu::contract_stubs::moe_grouped_gemm_backward_input(call);
    case quixicore::contract::OperationId::moe_grouped_gemm_backward_weight:
      return quixicore::xpu::contract_stubs::moe_grouped_gemm_backward_weight(call);
    case quixicore::contract::OperationId::moe_grouped_gemm_swiglu:
      return quixicore::xpu::contract_stubs::moe_grouped_gemm_swiglu(call);
    case quixicore::contract::OperationId::moe_grouped_qgemm:
      return quixicore::xpu::contract_stubs::moe_grouped_qgemm(call);
    case quixicore::contract::OperationId::moe_grouped_qswiglu:
      return quixicore::xpu::contract_stubs::moe_grouped_qswiglu(call);
    case quixicore::contract::OperationId::moe_route_grouped:
      return quixicore::xpu::contract_stubs::moe_route_grouped(call);
    case quixicore::contract::OperationId::moe_route_top_k_prefix_sum_permute:
      return quixicore::xpu::contract_stubs::moe_route_top_k_prefix_sum_permute(call);
    case quixicore::contract::OperationId::moe_unpermute_weighted_reduce:
      return quixicore::xpu::contract_stubs::moe_unpermute_weighted_reduce(call);
    case quixicore::contract::OperationId::mrope:
      return quixicore::xpu::contract_stubs::mrope(call);
    case quixicore::contract::OperationId::multi_codebook_sample:
      return quixicore::xpu::contract_stubs::multi_codebook_sample(call);
    case quixicore::contract::OperationId::multimodal_rope_nd:
      return quixicore::xpu::contract_stubs::multimodal_rope_nd(call);
    case quixicore::contract::OperationId::multimodal_stream_deinterleave:
      return quixicore::xpu::contract_stubs::multimodal_stream_deinterleave(call);
    case quixicore::contract::OperationId::multimodal_stream_interleave:
      return quixicore::xpu::contract_stubs::multimodal_stream_interleave(call);
    case quixicore::contract::OperationId::multiply:
      return quixicore::xpu::contract_stubs::multiply(call);
    case quixicore::contract::OperationId::multistream_logits_codebook_sample:
      return quixicore::xpu::contract_stubs::multistream_logits_codebook_sample(call);
    case quixicore::contract::OperationId::mxfp8_gemm:
      return quixicore::xpu::contract_stubs::mxfp8_gemm(call);
    case quixicore::contract::OperationId::non_max_suppression:
      return quixicore::xpu::contract_stubs::non_max_suppression(call);
    case quixicore::contract::OperationId::norm_quant:
      return quixicore::xpu::contract_stubs::norm_quant(call);
    case quixicore::contract::OperationId::nvfp4_gemm:
      return quixicore::xpu::contract_stubs::nvfp4_gemm(call);
    case quixicore::contract::OperationId::outer_product:
      return quixicore::xpu::contract_stubs::outer_product(call);
    case quixicore::contract::OperationId::overlap_add:
      return quixicore::xpu::contract_stubs::overlap_add(call);
    case quixicore::contract::OperationId::pad_2d:
      return quixicore::xpu::contract_stubs::pad_2d(call);
    case quixicore::contract::OperationId::pad_reflect_1d:
      return quixicore::xpu::contract_stubs::pad_reflect_1d(call);
    case quixicore::contract::OperationId::paged_attention_advanced:
      return quixicore::xpu::contract_stubs::paged_attention_advanced(call);
    case quixicore::contract::OperationId::paged_attention_bitnet_kv3:
      return quixicore::xpu::contract_stubs::paged_attention_bitnet_kv3(call);
    case quixicore::contract::OperationId::paged_attention_output_projection_residual:
      return quixicore::xpu::contract_stubs::paged_attention_output_projection_residual(call);
    case quixicore::contract::OperationId::paged_attention_q8_0:
      return quixicore::xpu::contract_stubs::paged_attention_q8_0(call);
    case quixicore::contract::OperationId::paged_attention_turboquant:
      return quixicore::xpu::contract_stubs::paged_attention_turboquant(call);
    case quixicore::contract::OperationId::patch_merge_layer_norm:
      return quixicore::xpu::contract_stubs::patch_merge_layer_norm(call);
    case quixicore::contract::OperationId::patchify_nd:
      return quixicore::xpu::contract_stubs::patchify_nd(call);
    case quixicore::contract::OperationId::patchify_projection_position:
      return quixicore::xpu::contract_stubs::patchify_projection_position(call);
    case quixicore::contract::OperationId::pixel_shuffle:
      return quixicore::xpu::contract_stubs::pixel_shuffle(call);
    case quixicore::contract::OperationId::pool1d:
      return quixicore::xpu::contract_stubs::pool1d(call);
    case quixicore::contract::OperationId::pool2d:
      return quixicore::xpu::contract_stubs::pool2d(call);
    case quixicore::contract::OperationId::pool2d_backward:
      return quixicore::xpu::contract_stubs::pool2d_backward(call);
    case quixicore::contract::OperationId::pool_tokens_by_position:
      return quixicore::xpu::contract_stubs::pool_tokens_by_position(call);
    case quixicore::contract::OperationId::prefix_append_attention:
      return quixicore::xpu::contract_stubs::prefix_append_attention(call);
    case quixicore::contract::OperationId::qgeglu:
      return quixicore::xpu::contract_stubs::qgeglu(call);
    case quixicore::contract::OperationId::qgemm:
      return quixicore::xpu::contract_stubs::qgemm(call);
    case quixicore::contract::OperationId::qgemm_backward_input:
      return quixicore::xpu::contract_stubs::qgemm_backward_input(call);
    case quixicore::contract::OperationId::qgemm_int:
      return quixicore::xpu::contract_stubs::qgemm_int(call);
    case quixicore::contract::OperationId::qgemm_q4q8:
      return quixicore::xpu::contract_stubs::qgemm_q4q8(call);
    case quixicore::contract::OperationId::qgemv:
      return quixicore::xpu::contract_stubs::qgemv(call);
    case quixicore::contract::OperationId::qgemv_qkv:
      return quixicore::xpu::contract_stubs::qgemv_qkv(call);
    case quixicore::contract::OperationId::qgemv_up_gate:
      return quixicore::xpu::contract_stubs::qgemv_up_gate(call);
    case quixicore::contract::OperationId::qgemv_up_gate_activation:
      return quixicore::xpu::contract_stubs::qgemv_up_gate_activation(call);
    case quixicore::contract::OperationId::qk_norm_rope:
      return quixicore::xpu::contract_stubs::qk_norm_rope(call);
    case quixicore::contract::OperationId::qk_norm_rope_attention:
      return quixicore::xpu::contract_stubs::qk_norm_rope_attention(call);
    case quixicore::contract::OperationId::qk_norm_rope_positioned:
      return quixicore::xpu::contract_stubs::qk_norm_rope_positioned(call);
    case quixicore::contract::OperationId::qkv_proj_fused:
      return quixicore::xpu::contract_stubs::qkv_proj_fused(call);
    case quixicore::contract::OperationId::qkv_projection_qk_norm_rope_kv_append:
      return quixicore::xpu::contract_stubs::qkv_projection_qk_norm_rope_kv_append(call);
    case quixicore::contract::OperationId::quantized_attention:
      return quixicore::xpu::contract_stubs::quantized_attention(call);
    case quixicore::contract::OperationId::quantized_embedding:
      return quixicore::xpu::contract_stubs::quantized_embedding(call);
    case quixicore::contract::OperationId::quantized_embedding_bag:
      return quixicore::xpu::contract_stubs::quantized_embedding_bag(call);
    case quixicore::contract::OperationId::quantized_lm_head_sample:
      return quixicore::xpu::contract_stubs::quantized_lm_head_sample(call);
    case quixicore::contract::OperationId::qwen_vision_rope_2d:
      return quixicore::xpu::contract_stubs::qwen_vision_rope_2d(call);
    case quixicore::contract::OperationId::ragged_pack:
      return quixicore::xpu::contract_stubs::ragged_pack(call);
    case quixicore::contract::OperationId::ragged_unpack:
      return quixicore::xpu::contract_stubs::ragged_unpack(call);
    case quixicore::contract::OperationId::reduce_mean:
      return quixicore::xpu::contract_stubs::reduce_mean(call);
    case quixicore::contract::OperationId::reduce_scatter_gemm:
      return quixicore::xpu::contract_stubs::reduce_scatter_gemm(call);
    case quixicore::contract::OperationId::reduce_sum:
      return quixicore::xpu::contract_stubs::reduce_sum(call);
    case quixicore::contract::OperationId::reduce_sum_all:
      return quixicore::xpu::contract_stubs::reduce_sum_all(call);
    case quixicore::contract::OperationId::repeat_2d:
      return quixicore::xpu::contract_stubs::repeat_2d(call);
    case quixicore::contract::OperationId::repeat_backward_2d:
      return quixicore::xpu::contract_stubs::repeat_backward_2d(call);
    case quixicore::contract::OperationId::residual_rms_norm_quant:
      return quixicore::xpu::contract_stubs::residual_rms_norm_quant(call);
    case quixicore::contract::OperationId::residual_vector_quantize_decode:
      return quixicore::xpu::contract_stubs::residual_vector_quantize_decode(call);
    case quixicore::contract::OperationId::residual_vector_quantize_encode:
      return quixicore::xpu::contract_stubs::residual_vector_quantize_encode(call);
    case quixicore::contract::OperationId::resize_bicubic:
      return quixicore::xpu::contract_stubs::resize_bicubic(call);
    case quixicore::contract::OperationId::resize_bilinear:
      return quixicore::xpu::contract_stubs::resize_bilinear(call);
    case quixicore::contract::OperationId::resize_normalize_layout_quant:
      return quixicore::xpu::contract_stubs::resize_normalize_layout_quant(call);
    case quixicore::contract::OperationId::rms_norm_backward:
      return quixicore::xpu::contract_stubs::rms_norm_backward(call);
    case quixicore::contract::OperationId::rms_norm_residual_next:
      return quixicore::xpu::contract_stubs::rms_norm_residual_next(call);
    case quixicore::contract::OperationId::rnnt_beam_step:
      return quixicore::xpu::contract_stubs::rnnt_beam_step(call);
    case quixicore::contract::OperationId::rnnt_joiner:
      return quixicore::xpu::contract_stubs::rnnt_joiner(call);
    case quixicore::contract::OperationId::roi_align:
      return quixicore::xpu::contract_stubs::roi_align(call);
    case quixicore::contract::OperationId::roll_2d:
      return quixicore::xpu::contract_stubs::roll_2d(call);
    case quixicore::contract::OperationId::rope_3d:
      return quixicore::xpu::contract_stubs::rope_3d(call);
    case quixicore::contract::OperationId::rotary_positioned:
      return quixicore::xpu::contract_stubs::rotary_positioned(call);
    case quixicore::contract::OperationId::rvq_distance_argmin_residual_update:
      return quixicore::xpu::contract_stubs::rvq_distance_argmin_residual_update(call);
    case quixicore::contract::OperationId::rwkv_wkv6:
      return quixicore::xpu::contract_stubs::rwkv_wkv6(call);
    case quixicore::contract::OperationId::rwkv_wkv7:
      return quixicore::xpu::contract_stubs::rwkv_wkv7(call);
    case quixicore::contract::OperationId::scale:
      return quixicore::xpu::contract_stubs::scale(call);
    case quixicore::contract::OperationId::set_rows:
      return quixicore::xpu::contract_stubs::set_rows(call);
    case quixicore::contract::OperationId::sgd:
      return quixicore::xpu::contract_stubs::sgd(call);
    case quixicore::contract::OperationId::sigmoid_mul:
      return quixicore::xpu::contract_stubs::sigmoid_mul(call);
    case quixicore::contract::OperationId::sigmoid_mul_backward:
      return quixicore::xpu::contract_stubs::sigmoid_mul_backward(call);
    case quixicore::contract::OperationId::silu_backward:
      return quixicore::xpu::contract_stubs::silu_backward(call);
    case quixicore::contract::OperationId::sine:
      return quixicore::xpu::contract_stubs::sine(call);
    case quixicore::contract::OperationId::softmax_backward:
      return quixicore::xpu::contract_stubs::softmax_backward(call);
    case quixicore::contract::OperationId::solve_lower_triangular:
      return quixicore::xpu::contract_stubs::solve_lower_triangular(call);
    case quixicore::contract::OperationId::space_to_depth_norm_linear:
      return quixicore::xpu::contract_stubs::space_to_depth_norm_linear(call);
    case quixicore::contract::OperationId::speculative_verify_accept_compact_kv:
      return quixicore::xpu::contract_stubs::speculative_verify_accept_compact_kv(call);
    case quixicore::contract::OperationId::square:
      return quixicore::xpu::contract_stubs::square(call);
    case quixicore::contract::OperationId::square_root:
      return quixicore::xpu::contract_stubs::square_root(call);
    case quixicore::contract::OperationId::ssd_chunked_backward:
      return quixicore::xpu::contract_stubs::ssd_chunked_backward(call);
    case quixicore::contract::OperationId::ssd_decode:
      return quixicore::xpu::contract_stubs::ssd_decode(call);
    case quixicore::contract::OperationId::stft:
      return quixicore::xpu::contract_stubs::stft(call);
    case quixicore::contract::OperationId::streaming_conv1d_state:
      return quixicore::xpu::contract_stubs::streaming_conv1d_state(call);
    case quixicore::contract::OperationId::subtract:
      return quixicore::xpu::contract_stubs::subtract(call);
    case quixicore::contract::OperationId::swiglu_oai:
      return quixicore::xpu::contract_stubs::swiglu_oai(call);
    case quixicore::contract::OperationId::temporal_upsample_conv3d:
      return quixicore::xpu::contract_stubs::temporal_upsample_conv3d(call);
    case quixicore::contract::OperationId::tensor_copy:
      return quixicore::xpu::contract_stubs::tensor_copy(call);
    case quixicore::contract::OperationId::tensor_set_4d:
      return quixicore::xpu::contract_stubs::tensor_set_4d(call);
    case quixicore::contract::OperationId::ternary_code_flip_count:
      return quixicore::xpu::contract_stubs::ternary_code_flip_count(call);
    case quixicore::contract::OperationId::ternary_pack:
      return quixicore::xpu::contract_stubs::ternary_pack(call);
    case quixicore::contract::OperationId::ternary_stats:
      return quixicore::xpu::contract_stubs::ternary_stats(call);
    case quixicore::contract::OperationId::ternary_unpack:
      return quixicore::xpu::contract_stubs::ternary_unpack(call);
    case quixicore::contract::OperationId::threshold_topk_indices:
      return quixicore::xpu::contract_stubs::threshold_topk_indices(call);
    case quixicore::contract::OperationId::timestep_embedding:
      return quixicore::xpu::contract_stubs::timestep_embedding(call);
    case quixicore::contract::OperationId::top_k_renorm:
      return quixicore::xpu::contract_stubs::top_k_renorm(call);
    case quixicore::contract::OperationId::top_p_renorm:
      return quixicore::xpu::contract_stubs::top_p_renorm(call);
    case quixicore::contract::OperationId::tq2_0_pack:
      return quixicore::xpu::contract_stubs::tq2_0_pack(call);
    case quixicore::contract::OperationId::tq2_0_unpack:
      return quixicore::xpu::contract_stubs::tq2_0_unpack(call);
    case quixicore::contract::OperationId::triangular_fill:
      return quixicore::xpu::contract_stubs::triangular_fill(call);
    case quixicore::contract::OperationId::turboquant:
      return quixicore::xpu::contract_stubs::turboquant(call);
    case quixicore::contract::OperationId::unary:
      return quixicore::xpu::contract_stubs::unary(call);
    case quixicore::contract::OperationId::unpatchify_nd:
      return quixicore::xpu::contract_stubs::unpatchify_nd(call);
    case quixicore::contract::OperationId::upsample_3d:
      return quixicore::xpu::contract_stubs::upsample_3d(call);
    case quixicore::contract::OperationId::upsample_conv2d:
      return quixicore::xpu::contract_stubs::upsample_conv2d(call);
    case quixicore::contract::OperationId::upscale_nearest_2d:
      return quixicore::xpu::contract_stubs::upscale_nearest_2d(call);
    case quixicore::contract::OperationId::value_clip:
      return quixicore::xpu::contract_stubs::value_clip(call);
    case quixicore::contract::OperationId::vision_patch_projection:
      return quixicore::xpu::contract_stubs::vision_patch_projection(call);
    case quixicore::contract::OperationId::vision_patch_projection_3d:
      return quixicore::xpu::contract_stubs::vision_patch_projection_3d(call);
    case quixicore::contract::OperationId::vision_rope_2d:
      return quixicore::xpu::contract_stubs::vision_rope_2d(call);
    case quixicore::contract::OperationId::window_attention:
      return quixicore::xpu::contract_stubs::window_attention(call);
    case quixicore::contract::OperationId::window_partition:
      return quixicore::xpu::contract_stubs::window_partition(call);
    case quixicore::contract::OperationId::window_rfft_power_mel_log:
      return quixicore::xpu::contract_stubs::window_rfft_power_mel_log(call);
    case quixicore::contract::OperationId::window_unpartition:
      return quixicore::xpu::contract_stubs::window_unpartition(call);
    default:
      break;
  }
  const auto name = quixicore::contract::operation_name(operation);
  return quixicore::contract::adapter_not_wired(
      name.empty() ? "unknown_operation" : name.data());
}

}  // namespace quixicore::xpu::contract_api
