#pragma once

// Generated by QuixiCore/tools/sync_kernel_contract.rb. Do not edit.
// These adapters are scaffolding only and make no implementation claim.

#include <array>

#include "quixicore/contract/kernel_abi.hpp"

namespace quixicore::xpu::contract_stubs {

using quixicore::contract::KernelCall;
using quixicore::contract::Status;
using quixicore::contract::StubDescriptor;

[[nodiscard]] inline Status accumulate(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("accumulate", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status adamw_masked(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adamw_masked", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status adaptive_norm_modulation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_norm_modulation", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_norm_modulation_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_norm_modulation_qkv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_rms_norm_modulation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_rms_norm_modulation", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_rms_norm_modulation_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_rms_norm_modulation_qkv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status add_id(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("add_id", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status add_relative_position_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("add_relative_position_2d", "no family claim");
}

[[nodiscard]] inline Status add_scalar(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("add_scalar", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status all_gather_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("all_gather_gemm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status all_reduce_rms_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("all_reduce_rms_norm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status arange(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("arange", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status argsort(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("argsort", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status attention_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status attention_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_gate_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status attention_with_lse(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_with_lse", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status audio_causal_depthwise_conv1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_causal_depthwise_conv1d", "no family claim");
}

[[nodiscard]] inline Status audio_conv1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_conv1d", "no family claim");
}

[[nodiscard]] inline Status audio_conv1d_direct(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_conv1d_direct", "no family claim");
}

[[nodiscard]] inline Status audio_depthwise_conv1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_depthwise_conv1d", "no family claim");
}

[[nodiscard]] inline Status audio_relative_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_relative_attention", "no family claim");
}

[[nodiscard]] inline Status audio_resample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_resample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status avg_pool2d_tokens(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("avg_pool2d_tokens", "no family claim");
}

[[nodiscard]] inline Status base_q_dequant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_dequant", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_embedding(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_embedding", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_gemv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_lm_head_argmax(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_lm_head_argmax", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_moe_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_moe_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_moe_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_moe_swiglu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_qkv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status base_q_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("base_q_swiglu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status based_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("based_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status biased_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("biased_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status broadcast(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("broadcast", "capability-gated family");
}

[[nodiscard]] inline Status calibration_absmax(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("calibration_absmax", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status causal_conv3d_cache_update(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("causal_conv3d_cache_update", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status causal_conv_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("causal_conv_gate_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status clamp(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("clamp", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status classifier_free_guidance_combine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("classifier_free_guidance_combine", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status classifier_free_guidance_scheduler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("classifier_free_guidance_scheduler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status col2im_1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("col2im_1d", "no family claim");
}

[[nodiscard]] inline Status col2im_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("col2im_2d", "no family claim");
}

[[nodiscard]] inline Status complex_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("complex_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status concat(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("concat", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv2d", "no family claim");
}

[[nodiscard]] inline Status conv3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv3d", "no family claim");
}

[[nodiscard]] inline Status conv_transpose_1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_1d", "no family claim");
}

[[nodiscard]] inline Status conv_transpose_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_2d", "no family claim");
}

[[nodiscard]] inline Status conv_transpose_overlap_add(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_overlap_add", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status cosine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cosine", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status count_equal(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("count_equal", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status cross_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cross_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status cross_entropy_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cross_entropy_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ctc_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ctc_decode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status cumulative_sum(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cumulative_sum", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status decode_cache_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_cache_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status decode_linear(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_linear", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status decode_linear_q8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_linear_q8", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status decode_linear_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_linear_residual", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status decode_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("decode_swiglu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status deformable_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("deformable_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status dense_gemm_ex(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dense_gemm_ex", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status depthwise_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("depthwise_conv2d", "no family claim");
}

[[nodiscard]] inline Status dequant_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dequant_gather", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status deterministic_noise(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("deterministic_noise", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status diag_embed(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diag_embed", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status diag_mask(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diag_mask", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status diffusion_scheduler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diffusion_scheduler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status divide(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("divide", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status down_projection_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("down_projection_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status downsample_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("downsample_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status downsample_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("downsample_conv2d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status dsv4_hc_comb(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dsv4_hc_comb", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status dsv4_hc_post(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dsv4_hc_post", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status dsv4_hc_pre(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dsv4_hc_pre", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status edge_mlp_256x7(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("edge_mlp_256x7", "no family claim");
}

[[nodiscard]] inline Status embedding_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("embedding_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status embedding_lookup_types(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("embedding_lookup_types", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status extract_patches_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("extract_patches_2d", "no family claim");
}

[[nodiscard]] inline Status extract_patches_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("extract_patches_3d", "no family claim");
}

[[nodiscard]] inline Status factorized_position_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("factorized_position_2d", "no family claim");
}

[[nodiscard]] inline Status fake_quant_float8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fake_quant_float8", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status fake_quant_int8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fake_quant_int8", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status fft_convolution(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fft_convolution", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status fill(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fill", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status flow_euler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("flow_euler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status flow_step_action_clamp_denormalize(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("flow_step_action_clamp_denormalize", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status fp8_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fp8_gemm", "experimental operation");
}

[[nodiscard]] inline Status fp8_scaled_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fp8_scaled_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gate_up_projection_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gate_up_projection_swiglu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status gated_linear_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gated_linear_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gdn_gate_beta(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gdn_gate_beta", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gdn_gated_rmsnorm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gdn_gated_rmsnorm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gdn_qkv_prepare(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gdn_qkv_prepare", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gdn_recurrence(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gdn_recurrence", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gdn_short_conv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gdn_short_conv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status geglu_projection(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("geglu_projection", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status gemm_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gemm_gate_residual", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status get_relative_position(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("get_relative_position", "no family claim");
}

[[nodiscard]] inline Status grammar_mask(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grammar_mask", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status grid_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grid_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status group_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("group_norm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status group_norm_silu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("group_norm_silu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status grouped_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grouped_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status hedgehog_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("hedgehog_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status im2col_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("im2col_2d", "no family claim");
}

[[nodiscard]] inline Status im2col_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("im2col_3d", "no family claim");
}

[[nodiscard]] inline Status indexer_k_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("indexer_k_gather", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status interpolate_position_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("interpolate_position_2d", "no family claim");
}

[[nodiscard]] inline Status istft(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("istft", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status joint_multimodal_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("joint_multimodal_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kd_ce_fused_bwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_ce_fused_bwd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kd_ce_fused_fwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_ce_fused_fwd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kd_kl_dense_bwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_dense_bwd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kd_kl_dense_fwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_dense_fwd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kd_kl_topk_bwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_topk_bwd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kd_kl_topk_fwd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kd_kl_topk_fwd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_compact(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_compact", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_copy_blocks_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_copy_blocks_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_gather_bitnet_kv3(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_gather_bitnet_kv3", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_gather_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_gather_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_offload(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_offload", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_scatter_bitnet_kv3(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_scatter_bitnet_kv3", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_scatter_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_scatter_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status l2_normalize(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("l2_normalize", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status leaky_relu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("leaky_relu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status linear_attention_unnormalized(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("linear_attention_unnormalized", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status linear_epilogue(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("linear_epilogue", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status lm_head_beam_advance(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lm_head_beam_advance", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status lm_head_candidates(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lm_head_candidates", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status lm_head_masked(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lm_head_masked", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status log_mel_spectrogram(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("log_mel_spectrogram", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status logarithm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("logarithm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status logits_bias_penalties_top_k_top_p_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("logits_bias_penalties_top_k_top_p_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status logits_softcap(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("logits_softcap", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status lora_apply(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lora_apply", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status lora_apply_direct_f16(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lora_apply_direct_f16", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status mamba2_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mamba2_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status masked_mean_pool_rms_l2(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("masked_mean_pool_rms_l2", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status mean_pool_rms_l2(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mean_pool_rms_l2", "no family claim");
}

[[nodiscard]] inline Status mixed_prefill_decode_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mixed_prefill_decode_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_all_to_all_dispatch(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_all_to_all_dispatch", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_finalize_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_finalize_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_gather_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_gather_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_grouped_gemm_backward_input(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_backward_input", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_grouped_gemm_backward_weight(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_backward_weight", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_grouped_gemm_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_swiglu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_grouped_qgemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_qgemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_grouped_qswiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_qswiglu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_route_grouped(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_grouped", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_route_top_k_prefix_sum_permute(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_top_k_prefix_sum_permute", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_unpermute_weighted_reduce(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_unpermute_weighted_reduce", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status mrope(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mrope", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status multi_codebook_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multi_codebook_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_rope_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_rope_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_stream_deinterleave(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_stream_deinterleave", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_stream_interleave(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_stream_interleave", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multiply(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multiply", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status multistream_logits_codebook_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multistream_logits_codebook_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status mxfp8_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mxfp8_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status non_max_suppression(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("non_max_suppression", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status norm_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("norm_quant", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status nvfp4_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("nvfp4_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status outer_product(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("outer_product", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status overlap_add(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("overlap_add", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pad_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pad_2d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status pad_reflect_1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pad_reflect_1d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status paged_attention_advanced(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_advanced", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status paged_attention_bitnet_kv3(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_bitnet_kv3", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status paged_attention_output_projection_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_output_projection_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status paged_attention_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status paged_attention_turboquant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_turboquant", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status patch_merge_layer_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patch_merge_layer_norm", "no family claim");
}

[[nodiscard]] inline Status patchify_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patchify_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status patchify_projection_position(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patchify_projection_position", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pixel_shuffle(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pixel_shuffle", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pool1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool1d", "no family claim");
}

[[nodiscard]] inline Status pool2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool2d", "no family claim");
}

[[nodiscard]] inline Status pool2d_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool2d_backward", "no family claim");
}

[[nodiscard]] inline Status pool_tokens_by_position(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pool_tokens_by_position", "no family claim");
}

[[nodiscard]] inline Status prefix_append_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("prefix_append_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status qgeglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgeglu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemm_backward_input(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm_backward_input", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemm_int(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm_int", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemm_q4q8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemm_q4q8", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemv_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv_qkv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemv_up_gate(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv_up_gate", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qgemv_up_gate_activation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qgemv_up_gate_activation", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qk_norm_rope(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qk_norm_rope_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status qk_norm_rope_positioned(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope_positioned", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qkv_proj_fused(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qkv_proj_fused", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qkv_projection_qk_norm_rope_kv_append(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qkv_projection_qk_norm_rope_kv_append", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status quantized_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantized_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status quantized_embedding(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantized_embedding", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status quantized_embedding_bag(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantized_embedding_bag", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status quantized_lm_head_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantized_lm_head_sample", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status qwen_vision_rope_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qwen_vision_rope_2d", "no family claim");
}

[[nodiscard]] inline Status ragged_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ragged_pack", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status ragged_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ragged_unpack", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status reduce_mean(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_mean", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status reduce_scatter_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_scatter_gemm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status reduce_sum(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_sum", "capability-gated family");
}

[[nodiscard]] inline Status reduce_sum_all(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_sum_all", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status repeat_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("repeat_2d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status repeat_backward_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("repeat_backward_2d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status residual_rms_norm_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_rms_norm_quant", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_vector_quantize_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_vector_quantize_decode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_vector_quantize_encode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_vector_quantize_encode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_bicubic(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_bicubic", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_bilinear(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_bilinear", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_normalize_layout_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_normalize_layout_quant", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rms_norm_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rms_norm_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status rms_norm_residual_next(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rms_norm_residual_next", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status rnnt_beam_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rnnt_beam_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rnnt_joiner(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rnnt_joiner", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status roi_align(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("roi_align", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status roll_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("roll_2d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status rope_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rope_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rotary_positioned(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rotary_positioned", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status rvq_distance_argmin_residual_update(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rvq_distance_argmin_residual_update", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rwkv_wkv6(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rwkv_wkv6", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status rwkv_wkv7(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rwkv_wkv7", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status scale(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("scale", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status set_rows(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("set_rows", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status sgd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sgd", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status sigmoid_mul(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sigmoid_mul", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status sigmoid_mul_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sigmoid_mul_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status silu_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("silu_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status sine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sine", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status softmax_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("softmax_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status solve_lower_triangular(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("solve_lower_triangular", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status space_to_depth_norm_linear(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("space_to_depth_norm_linear", "no family claim");
}

[[nodiscard]] inline Status speculative_verify_accept_compact_kv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("speculative_verify_accept_compact_kv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status square(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("square", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status square_root(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("square_root", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ssd_chunked_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ssd_chunked_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ssd_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ssd_decode", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status stft(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("stft", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status streaming_conv1d_state(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("streaming_conv1d_state", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status subtract(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("subtract", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status swiglu_oai(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("swiglu_oai", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status temporal_upsample_conv3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("temporal_upsample_conv3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status tensor_copy(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tensor_copy", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status tensor_set_4d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tensor_set_4d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ternary_code_flip_count(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_code_flip_count", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ternary_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_pack", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ternary_stats(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_stats", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ternary_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ternary_unpack", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status threshold_topk_indices(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("threshold_topk_indices", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status timestep_embedding(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("timestep_embedding", "no family claim");
}

[[nodiscard]] inline Status top_k_renorm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("top_k_renorm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status top_p_renorm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("top_p_renorm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status tq2_0_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tq2_0_pack", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status tq2_0_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("tq2_0_unpack", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status triangular_fill(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("triangular_fill", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status turboquant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("turboquant", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status unary(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("unary", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status unpatchify_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("unpatchify_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upsample_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upsample_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upsample_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upsample_conv2d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upscale_nearest_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upscale_nearest_2d", "no family claim");
}

[[nodiscard]] inline Status value_clip(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("value_clip", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status vision_patch_projection(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("vision_patch_projection", "no family claim");
}

[[nodiscard]] inline Status vision_patch_projection_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("vision_patch_projection_3d", "no family claim");
}

[[nodiscard]] inline Status vision_rope_2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("vision_rope_2d", "no family claim");
}

[[nodiscard]] inline Status window_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status window_partition(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_partition", "no family claim");
}

[[nodiscard]] inline Status window_rfft_power_mel_log(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_rfft_power_mel_log", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status window_unpartition(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_unpartition", "no family claim");
}

inline constexpr std::array<StubDescriptor, 273> kStubs{{
    {"accumulate", "utils", "partial family; canonical operation not implemented", &accumulate},
    {"adamw_masked", "optimizers", "partial family; canonical operation not implemented", &adamw_masked},
    {"adaptive_norm_modulation", "diffusion", "planned contract; no backend implementation evidence", &adaptive_norm_modulation},
    {"adaptive_norm_modulation_qkv", "diffusion", "planned contract; no backend implementation evidence", &adaptive_norm_modulation_qkv},
    {"adaptive_rms_norm_modulation", "diffusion", "planned contract; no backend implementation evidence", &adaptive_rms_norm_modulation},
    {"adaptive_rms_norm_modulation_qkv", "diffusion", "planned contract; no backend implementation evidence", &adaptive_rms_norm_modulation_qkv},
    {"add_id", "utils", "partial family; canonical operation not implemented", &add_id},
    {"add_relative_position_2d", "vision", "no family claim", &add_relative_position_2d},
    {"add_scalar", "utils", "partial family; canonical operation not implemented", &add_scalar},
    {"all_gather_gemm", "collectives", "planned contract; no backend implementation evidence", &all_gather_gemm},
    {"all_reduce_rms_norm", "collectives", "planned contract; no backend implementation evidence", &all_reduce_rms_norm},
    {"arange", "utils", "partial family; canonical operation not implemented", &arange},
    {"argsort", "utils", "partial family; canonical operation not implemented", &argsort},
    {"attention_backward", "attention", "partial family; canonical operation not implemented", &attention_backward},
    {"attention_gate_residual", "attention", "planned contract; no backend implementation evidence", &attention_gate_residual},
    {"attention_with_lse", "attention", "partial family; canonical operation not implemented", &attention_with_lse},
    {"audio_causal_depthwise_conv1d", "audio", "no family claim", &audio_causal_depthwise_conv1d},
    {"audio_conv1d", "audio", "no family claim", &audio_conv1d},
    {"audio_conv1d_direct", "audio", "no family claim", &audio_conv1d_direct},
    {"audio_depthwise_conv1d", "audio", "no family claim", &audio_depthwise_conv1d},
    {"audio_relative_attention", "audio", "no family claim", &audio_relative_attention},
    {"audio_resample", "audio", "planned contract; no backend implementation evidence", &audio_resample},
    {"avg_pool2d_tokens", "vision", "no family claim", &avg_pool2d_tokens},
    {"base_q_dequant", "quantization", "partial family; canonical operation not implemented", &base_q_dequant},
    {"base_q_embedding", "quantization", "partial family; canonical operation not implemented", &base_q_embedding},
    {"base_q_gemm", "quantization", "partial family; canonical operation not implemented", &base_q_gemm},
    {"base_q_gemv", "quantization", "partial family; canonical operation not implemented", &base_q_gemv},
    {"base_q_lm_head_argmax", "quantization", "partial family; canonical operation not implemented", &base_q_lm_head_argmax},
    {"base_q_moe_gemm", "quantization", "partial family; canonical operation not implemented", &base_q_moe_gemm},
    {"base_q_moe_swiglu", "quantization", "partial family; canonical operation not implemented", &base_q_moe_swiglu},
    {"base_q_qkv", "quantization", "partial family; canonical operation not implemented", &base_q_qkv},
    {"base_q_swiglu", "quantization", "partial family; canonical operation not implemented", &base_q_swiglu},
    {"based_attention", "linear_attention", "partial family; canonical operation not implemented", &based_attention},
    {"biased_attention", "attention", "partial family; canonical operation not implemented", &biased_attention},
    {"broadcast", "collectives", "capability-gated family", &broadcast},
    {"calibration_absmax", "quantization", "partial family; canonical operation not implemented", &calibration_absmax},
    {"causal_conv3d_cache_update", "convolution", "planned contract; no backend implementation evidence", &causal_conv3d_cache_update},
    {"causal_conv_gate_residual", "audio", "planned contract; no backend implementation evidence", &causal_conv_gate_residual},
    {"clamp", "utils", "partial family; canonical operation not implemented", &clamp},
    {"classifier_free_guidance_combine", "diffusion", "planned contract; no backend implementation evidence", &classifier_free_guidance_combine},
    {"classifier_free_guidance_scheduler_step", "diffusion", "planned contract; no backend implementation evidence", &classifier_free_guidance_scheduler_step},
    {"col2im_1d", "convolution", "no family claim", &col2im_1d},
    {"col2im_2d", "convolution", "no family claim", &col2im_2d},
    {"complex_gemm", "matmul", "partial family; canonical operation not implemented", &complex_gemm},
    {"concat", "utils", "partial family; canonical operation not implemented", &concat},
    {"conv2d", "convolution", "no family claim", &conv2d},
    {"conv3d", "convolution", "no family claim", &conv3d},
    {"conv_transpose_1d", "convolution", "no family claim", &conv_transpose_1d},
    {"conv_transpose_2d", "convolution", "no family claim", &conv_transpose_2d},
    {"conv_transpose_overlap_add", "audio", "planned contract; no backend implementation evidence", &conv_transpose_overlap_add},
    {"cosine", "utils", "partial family; canonical operation not implemented", &cosine},
    {"count_equal", "utils", "partial family; canonical operation not implemented", &count_equal},
    {"cross_attention", "attention", "partial family; canonical operation not implemented", &cross_attention},
    {"cross_entropy_backward", "utils", "partial family; canonical operation not implemented", &cross_entropy_backward},
    {"ctc_decode", "audio", "planned contract; no backend implementation evidence", &ctc_decode},
    {"cumulative_sum", "utils", "partial family; canonical operation not implemented", &cumulative_sum},
    {"decode_cache_attention", "attention", "partial family; canonical operation not implemented", &decode_cache_attention},
    {"decode_linear", "matmul", "partial family; canonical operation not implemented", &decode_linear},
    {"decode_linear_q8", "matmul", "partial family; canonical operation not implemented", &decode_linear_q8},
    {"decode_linear_residual", "matmul", "partial family; canonical operation not implemented", &decode_linear_residual},
    {"decode_swiglu", "matmul", "partial family; canonical operation not implemented", &decode_swiglu},
    {"deformable_attention", "vision", "planned contract; no backend implementation evidence", &deformable_attention},
    {"dense_gemm_ex", "matmul", "partial family; canonical operation not implemented", &dense_gemm_ex},
    {"depthwise_conv2d", "convolution", "no family claim", &depthwise_conv2d},
    {"dequant_gather", "quantization", "partial family; canonical operation not implemented", &dequant_gather},
    {"deterministic_noise", "diffusion", "planned contract; no backend implementation evidence", &deterministic_noise},
    {"diag_embed", "utils", "partial family; canonical operation not implemented", &diag_embed},
    {"diag_mask", "utils", "partial family; canonical operation not implemented", &diag_mask},
    {"diffusion_scheduler_step", "diffusion", "planned contract; no backend implementation evidence", &diffusion_scheduler_step},
    {"divide", "utils", "partial family; canonical operation not implemented", &divide},
    {"down_projection_residual", "matmul", "planned contract; no backend implementation evidence", &down_projection_residual},
    {"downsample_3d", "convolution", "planned contract; no backend implementation evidence", &downsample_3d},
    {"downsample_conv2d", "convolution", "planned contract; no backend implementation evidence", &downsample_conv2d},
    {"dsv4_hc_comb", "ssm", "partial family; canonical operation not implemented", &dsv4_hc_comb},
    {"dsv4_hc_post", "ssm", "partial family; canonical operation not implemented", &dsv4_hc_post},
    {"dsv4_hc_pre", "ssm", "partial family; canonical operation not implemented", &dsv4_hc_pre},
    {"edge_mlp_256x7", "vision", "no family claim", &edge_mlp_256x7},
    {"embedding_backward", "serving", "partial family; canonical operation not implemented", &embedding_backward},
    {"embedding_lookup_types", "serving", "partial family; canonical operation not implemented", &embedding_lookup_types},
    {"extract_patches_2d", "vision", "no family claim", &extract_patches_2d},
    {"extract_patches_3d", "vision", "no family claim", &extract_patches_3d},
    {"factorized_position_2d", "vision", "no family claim", &factorized_position_2d},
    {"fake_quant_float8", "quantization", "partial family; canonical operation not implemented", &fake_quant_float8},
    {"fake_quant_int8", "quantization", "partial family; canonical operation not implemented", &fake_quant_int8},
    {"fft_convolution", "ssm", "partial family; canonical operation not implemented", &fft_convolution},
    {"fill", "utils", "partial family; canonical operation not implemented", &fill},
    {"flow_euler_step", "diffusion", "planned contract; no backend implementation evidence", &flow_euler_step},
    {"flow_step_action_clamp_denormalize", "vla_world_models", "planned contract; no backend implementation evidence", &flow_step_action_clamp_denormalize},
    {"fp8_gemm", "quantization", "experimental operation", &fp8_gemm},
    {"fp8_scaled_gemm", "matmul", "partial family; canonical operation not implemented", &fp8_scaled_gemm},
    {"gate_up_projection_swiglu", "matmul", "planned contract; no backend implementation evidence", &gate_up_projection_swiglu},
    {"gated_linear_attention", "linear_attention", "partial family; canonical operation not implemented", &gated_linear_attention},
    {"gdn_gate_beta", "linear_attention", "partial family; canonical operation not implemented", &gdn_gate_beta},
    {"gdn_gated_rmsnorm", "linear_attention", "partial family; canonical operation not implemented", &gdn_gated_rmsnorm},
    {"gdn_qkv_prepare", "linear_attention", "partial family; canonical operation not implemented", &gdn_qkv_prepare},
    {"gdn_recurrence", "linear_attention", "partial family; canonical operation not implemented", &gdn_recurrence},
    {"gdn_short_conv", "linear_attention", "partial family; canonical operation not implemented", &gdn_short_conv},
    {"geglu_projection", "matmul", "planned contract; no backend implementation evidence", &geglu_projection},
    {"gemm_gate_residual", "matmul", "partial family; canonical operation not implemented", &gemm_gate_residual},
    {"get_relative_position", "vision", "no family claim", &get_relative_position},
    {"grammar_mask", "sampling", "planned contract; no backend implementation evidence", &grammar_mask},
    {"grid_sample", "vision", "planned contract; no backend implementation evidence", &grid_sample},
    {"group_norm", "utils", "partial family; canonical operation not implemented", &group_norm},
    {"group_norm_silu", "convolution", "planned contract; no backend implementation evidence", &group_norm_silu},
    {"grouped_gemm", "matmul", "partial family; canonical operation not implemented", &grouped_gemm},
    {"hedgehog_attention", "linear_attention", "partial family; canonical operation not implemented", &hedgehog_attention},
    {"im2col_2d", "convolution", "no family claim", &im2col_2d},
    {"im2col_3d", "convolution", "no family claim", &im2col_3d},
    {"indexer_k_gather", "serving", "partial family; canonical operation not implemented", &indexer_k_gather},
    {"interpolate_position_2d", "vision", "no family claim", &interpolate_position_2d},
    {"istft", "audio", "planned contract; no backend implementation evidence", &istft},
    {"joint_multimodal_attention", "multimodal", "planned contract; no backend implementation evidence", &joint_multimodal_attention},
    {"kd_ce_fused_bwd", "utils", "partial family; canonical operation not implemented", &kd_ce_fused_bwd},
    {"kd_ce_fused_fwd", "utils", "partial family; canonical operation not implemented", &kd_ce_fused_fwd},
    {"kd_kl_dense_bwd", "utils", "partial family; canonical operation not implemented", &kd_kl_dense_bwd},
    {"kd_kl_dense_fwd", "utils", "partial family; canonical operation not implemented", &kd_kl_dense_fwd},
    {"kd_kl_topk_bwd", "utils", "partial family; canonical operation not implemented", &kd_kl_topk_bwd},
    {"kd_kl_topk_fwd", "utils", "partial family; canonical operation not implemented", &kd_kl_topk_fwd},
    {"kv_cache_compact", "serving", "planned contract; no backend implementation evidence", &kv_cache_compact},
    {"kv_cache_copy_blocks_q8_0", "serving", "partial family; canonical operation not implemented", &kv_cache_copy_blocks_q8_0},
    {"kv_cache_gather_bitnet_kv3", "serving", "partial family; canonical operation not implemented", &kv_cache_gather_bitnet_kv3},
    {"kv_cache_gather_q8_0", "serving", "partial family; canonical operation not implemented", &kv_cache_gather_q8_0},
    {"kv_cache_offload", "serving", "planned contract; no backend implementation evidence", &kv_cache_offload},
    {"kv_cache_scatter_bitnet_kv3", "serving", "partial family; canonical operation not implemented", &kv_cache_scatter_bitnet_kv3},
    {"kv_cache_scatter_q8_0", "serving", "partial family; canonical operation not implemented", &kv_cache_scatter_q8_0},
    {"l2_normalize", "utils", "partial family; canonical operation not implemented", &l2_normalize},
    {"leaky_relu", "activations", "partial family; canonical operation not implemented", &leaky_relu},
    {"linear_attention_unnormalized", "linear_attention", "partial family; canonical operation not implemented", &linear_attention_unnormalized},
    {"linear_epilogue", "matmul", "partial family; canonical operation not implemented", &linear_epilogue},
    {"lm_head_beam_advance", "quantization", "partial family; canonical operation not implemented", &lm_head_beam_advance},
    {"lm_head_candidates", "quantization", "partial family; canonical operation not implemented", &lm_head_candidates},
    {"lm_head_masked", "quantization", "partial family; canonical operation not implemented", &lm_head_masked},
    {"log_mel_spectrogram", "audio", "planned contract; no backend implementation evidence", &log_mel_spectrogram},
    {"logarithm", "utils", "partial family; canonical operation not implemented", &logarithm},
    {"logits_bias_penalties_top_k_top_p_sample", "sampling", "planned contract; no backend implementation evidence", &logits_bias_penalties_top_k_top_p_sample},
    {"logits_softcap", "sampling", "partial family; canonical operation not implemented", &logits_softcap},
    {"lora_apply", "matmul", "partial family; canonical operation not implemented", &lora_apply},
    {"lora_apply_direct_f16", "matmul", "partial family; canonical operation not implemented", &lora_apply_direct_f16},
    {"mamba2_backward", "ssm", "partial family; canonical operation not implemented", &mamba2_backward},
    {"masked_mean_pool_rms_l2", "serving", "partial family; canonical operation not implemented", &masked_mean_pool_rms_l2},
    {"mean_pool_rms_l2", "pooling", "no family claim", &mean_pool_rms_l2},
    {"mixed_prefill_decode_attention", "attention", "planned contract; no backend implementation evidence", &mixed_prefill_decode_attention},
    {"moe_all_to_all_dispatch", "collectives", "planned contract; no backend implementation evidence", &moe_all_to_all_dispatch},
    {"moe_finalize_backward", "moe", "partial family; canonical operation not implemented", &moe_finalize_backward},
    {"moe_gather_backward", "moe", "partial family; canonical operation not implemented", &moe_gather_backward},
    {"moe_grouped_gemm_backward_input", "moe", "partial family; canonical operation not implemented", &moe_grouped_gemm_backward_input},
    {"moe_grouped_gemm_backward_weight", "moe", "partial family; canonical operation not implemented", &moe_grouped_gemm_backward_weight},
    {"moe_grouped_gemm_swiglu", "moe", "planned contract; no backend implementation evidence", &moe_grouped_gemm_swiglu},
    {"moe_grouped_qgemm", "moe", "partial family; canonical operation not implemented", &moe_grouped_qgemm},
    {"moe_grouped_qswiglu", "moe", "partial family; canonical operation not implemented", &moe_grouped_qswiglu},
    {"moe_route_grouped", "moe", "partial family; canonical operation not implemented", &moe_route_grouped},
    {"moe_route_top_k_prefix_sum_permute", "moe", "planned contract; no backend implementation evidence", &moe_route_top_k_prefix_sum_permute},
    {"moe_unpermute_weighted_reduce", "moe", "planned contract; no backend implementation evidence", &moe_unpermute_weighted_reduce},
    {"mrope", "attention", "partial family; canonical operation not implemented", &mrope},
    {"multi_codebook_sample", "audio", "planned contract; no backend implementation evidence", &multi_codebook_sample},
    {"multimodal_rope_nd", "multimodal", "planned contract; no backend implementation evidence", &multimodal_rope_nd},
    {"multimodal_stream_deinterleave", "multimodal", "planned contract; no backend implementation evidence", &multimodal_stream_deinterleave},
    {"multimodal_stream_interleave", "multimodal", "planned contract; no backend implementation evidence", &multimodal_stream_interleave},
    {"multiply", "utils", "partial family; canonical operation not implemented", &multiply},
    {"multistream_logits_codebook_sample", "audio", "planned contract; no backend implementation evidence", &multistream_logits_codebook_sample},
    {"mxfp8_gemm", "matmul", "partial family; canonical operation not implemented", &mxfp8_gemm},
    {"non_max_suppression", "vision", "planned contract; no backend implementation evidence", &non_max_suppression},
    {"norm_quant", "norms", "partial family; canonical operation not implemented", &norm_quant},
    {"nvfp4_gemm", "matmul", "partial family; canonical operation not implemented", &nvfp4_gemm},
    {"outer_product", "utils", "partial family; canonical operation not implemented", &outer_product},
    {"overlap_add", "audio", "planned contract; no backend implementation evidence", &overlap_add},
    {"pad_2d", "utils", "partial family; canonical operation not implemented", &pad_2d},
    {"pad_reflect_1d", "utils", "partial family; canonical operation not implemented", &pad_reflect_1d},
    {"paged_attention_advanced", "serving", "partial family; canonical operation not implemented", &paged_attention_advanced},
    {"paged_attention_bitnet_kv3", "serving", "partial family; canonical operation not implemented", &paged_attention_bitnet_kv3},
    {"paged_attention_output_projection_residual", "attention", "planned contract; no backend implementation evidence", &paged_attention_output_projection_residual},
    {"paged_attention_q8_0", "attention", "partial family; canonical operation not implemented", &paged_attention_q8_0},
    {"paged_attention_turboquant", "serving", "partial family; canonical operation not implemented", &paged_attention_turboquant},
    {"patch_merge_layer_norm", "vision", "no family claim", &patch_merge_layer_norm},
    {"patchify_nd", "diffusion", "planned contract; no backend implementation evidence", &patchify_nd},
    {"patchify_projection_position", "vision", "planned contract; no backend implementation evidence", &patchify_projection_position},
    {"pixel_shuffle", "vision", "planned contract; no backend implementation evidence", &pixel_shuffle},
    {"pool1d", "convolution", "no family claim", &pool1d},
    {"pool2d", "convolution", "no family claim", &pool2d},
    {"pool2d_backward", "convolution", "no family claim", &pool2d_backward},
    {"pool_tokens_by_position", "vision", "no family claim", &pool_tokens_by_position},
    {"prefix_append_attention", "attention", "planned contract; no backend implementation evidence", &prefix_append_attention},
    {"qgeglu", "quantization", "partial family; canonical operation not implemented", &qgeglu},
    {"qgemm", "quantization", "partial family; canonical operation not implemented", &qgemm},
    {"qgemm_backward_input", "quantization", "partial family; canonical operation not implemented", &qgemm_backward_input},
    {"qgemm_int", "quantization", "partial family; canonical operation not implemented", &qgemm_int},
    {"qgemm_q4q8", "quantization", "partial family; canonical operation not implemented", &qgemm_q4q8},
    {"qgemv", "quantization", "partial family; canonical operation not implemented", &qgemv},
    {"qgemv_qkv", "quantization", "partial family; canonical operation not implemented", &qgemv_qkv},
    {"qgemv_up_gate", "quantization", "partial family; canonical operation not implemented", &qgemv_up_gate},
    {"qgemv_up_gate_activation", "quantization", "partial family; canonical operation not implemented", &qgemv_up_gate_activation},
    {"qk_norm_rope", "norms", "partial family; canonical operation not implemented", &qk_norm_rope},
    {"qk_norm_rope_attention", "attention", "planned contract; no backend implementation evidence", &qk_norm_rope_attention},
    {"qk_norm_rope_positioned", "norms", "partial family; canonical operation not implemented", &qk_norm_rope_positioned},
    {"qkv_proj_fused", "quantization", "partial family; canonical operation not implemented", &qkv_proj_fused},
    {"qkv_projection_qk_norm_rope_kv_append", "attention", "planned contract; no backend implementation evidence", &qkv_projection_qk_norm_rope_kv_append},
    {"quantized_attention", "serving", "partial family; canonical operation not implemented", &quantized_attention},
    {"quantized_embedding", "quantization", "partial family; canonical operation not implemented", &quantized_embedding},
    {"quantized_embedding_bag", "quantization", "partial family; canonical operation not implemented", &quantized_embedding_bag},
    {"quantized_lm_head_sample", "quantization", "partial family; canonical operation not implemented", &quantized_lm_head_sample},
    {"qwen_vision_rope_2d", "vision", "no family claim", &qwen_vision_rope_2d},
    {"ragged_pack", "multimodal", "planned contract; no backend implementation evidence", &ragged_pack},
    {"ragged_unpack", "multimodal", "planned contract; no backend implementation evidence", &ragged_unpack},
    {"reduce_mean", "utils", "partial family; canonical operation not implemented", &reduce_mean},
    {"reduce_scatter_gemm", "collectives", "planned contract; no backend implementation evidence", &reduce_scatter_gemm},
    {"reduce_sum", "collectives", "capability-gated family", &reduce_sum},
    {"reduce_sum_all", "utils", "partial family; canonical operation not implemented", &reduce_sum_all},
    {"repeat_2d", "utils", "partial family; canonical operation not implemented", &repeat_2d},
    {"repeat_backward_2d", "utils", "partial family; canonical operation not implemented", &repeat_backward_2d},
    {"residual_rms_norm_quant", "norms", "planned contract; no backend implementation evidence", &residual_rms_norm_quant},
    {"residual_vector_quantize_decode", "audio", "planned contract; no backend implementation evidence", &residual_vector_quantize_decode},
    {"residual_vector_quantize_encode", "audio", "planned contract; no backend implementation evidence", &residual_vector_quantize_encode},
    {"resize_bicubic", "vision", "planned contract; no backend implementation evidence", &resize_bicubic},
    {"resize_bilinear", "vision", "planned contract; no backend implementation evidence", &resize_bilinear},
    {"resize_normalize_layout_quant", "vision", "planned contract; no backend implementation evidence", &resize_normalize_layout_quant},
    {"rms_norm_backward", "norms", "partial family; canonical operation not implemented", &rms_norm_backward},
    {"rms_norm_residual_next", "norms", "partial family; canonical operation not implemented", &rms_norm_residual_next},
    {"rnnt_beam_step", "audio", "planned contract; no backend implementation evidence", &rnnt_beam_step},
    {"rnnt_joiner", "audio", "planned contract; no backend implementation evidence", &rnnt_joiner},
    {"roi_align", "vision", "planned contract; no backend implementation evidence", &roi_align},
    {"roll_2d", "utils", "partial family; canonical operation not implemented", &roll_2d},
    {"rope_3d", "diffusion", "planned contract; no backend implementation evidence", &rope_3d},
    {"rotary_positioned", "attention", "partial family; canonical operation not implemented", &rotary_positioned},
    {"rvq_distance_argmin_residual_update", "audio", "planned contract; no backend implementation evidence", &rvq_distance_argmin_residual_update},
    {"rwkv_wkv6", "linear_attention", "partial family; canonical operation not implemented", &rwkv_wkv6},
    {"rwkv_wkv7", "linear_attention", "partial family; canonical operation not implemented", &rwkv_wkv7},
    {"scale", "utils", "partial family; canonical operation not implemented", &scale},
    {"set_rows", "utils", "partial family; canonical operation not implemented", &set_rows},
    {"sgd", "optimizers", "partial family; canonical operation not implemented", &sgd},
    {"sigmoid_mul", "activations", "partial family; canonical operation not implemented", &sigmoid_mul},
    {"sigmoid_mul_backward", "activations", "partial family; canonical operation not implemented", &sigmoid_mul_backward},
    {"silu_backward", "activations", "partial family; canonical operation not implemented", &silu_backward},
    {"sine", "utils", "partial family; canonical operation not implemented", &sine},
    {"softmax_backward", "activations", "partial family; canonical operation not implemented", &softmax_backward},
    {"solve_lower_triangular", "utils", "partial family; canonical operation not implemented", &solve_lower_triangular},
    {"space_to_depth_norm_linear", "vision", "no family claim", &space_to_depth_norm_linear},
    {"speculative_verify_accept_compact_kv", "serving", "planned contract; no backend implementation evidence", &speculative_verify_accept_compact_kv},
    {"square", "utils", "partial family; canonical operation not implemented", &square},
    {"square_root", "utils", "partial family; canonical operation not implemented", &square_root},
    {"ssd_chunked_backward", "ssm", "partial family; canonical operation not implemented", &ssd_chunked_backward},
    {"ssd_decode", "ssm", "partial family; canonical operation not implemented", &ssd_decode},
    {"stft", "audio", "planned contract; no backend implementation evidence", &stft},
    {"streaming_conv1d_state", "audio", "planned contract; no backend implementation evidence", &streaming_conv1d_state},
    {"subtract", "utils", "partial family; canonical operation not implemented", &subtract},
    {"swiglu_oai", "activations", "partial family; canonical operation not implemented", &swiglu_oai},
    {"temporal_upsample_conv3d", "convolution", "planned contract; no backend implementation evidence", &temporal_upsample_conv3d},
    {"tensor_copy", "utils", "partial family; canonical operation not implemented", &tensor_copy},
    {"tensor_set_4d", "utils", "partial family; canonical operation not implemented", &tensor_set_4d},
    {"ternary_code_flip_count", "quantization", "partial family; canonical operation not implemented", &ternary_code_flip_count},
    {"ternary_pack", "quantization", "partial family; canonical operation not implemented", &ternary_pack},
    {"ternary_stats", "quantization", "partial family; canonical operation not implemented", &ternary_stats},
    {"ternary_unpack", "quantization", "partial family; canonical operation not implemented", &ternary_unpack},
    {"threshold_topk_indices", "utils", "partial family; canonical operation not implemented", &threshold_topk_indices},
    {"timestep_embedding", "vision", "no family claim", &timestep_embedding},
    {"top_k_renorm", "sampling", "partial family; canonical operation not implemented", &top_k_renorm},
    {"top_p_renorm", "sampling", "partial family; canonical operation not implemented", &top_p_renorm},
    {"tq2_0_pack", "quantization", "partial family; canonical operation not implemented", &tq2_0_pack},
    {"tq2_0_unpack", "quantization", "partial family; canonical operation not implemented", &tq2_0_unpack},
    {"triangular_fill", "utils", "partial family; canonical operation not implemented", &triangular_fill},
    {"turboquant", "quantization", "partial family; canonical operation not implemented", &turboquant},
    {"unary", "activations", "partial family; canonical operation not implemented", &unary},
    {"unpatchify_nd", "diffusion", "planned contract; no backend implementation evidence", &unpatchify_nd},
    {"upsample_3d", "convolution", "planned contract; no backend implementation evidence", &upsample_3d},
    {"upsample_conv2d", "convolution", "planned contract; no backend implementation evidence", &upsample_conv2d},
    {"upscale_nearest_2d", "vision", "no family claim", &upscale_nearest_2d},
    {"value_clip", "activations", "partial family; canonical operation not implemented", &value_clip},
    {"vision_patch_projection", "vision", "no family claim", &vision_patch_projection},
    {"vision_patch_projection_3d", "vision", "no family claim", &vision_patch_projection_3d},
    {"vision_rope_2d", "vision", "no family claim", &vision_rope_2d},
    {"window_attention", "attention", "partial family; canonical operation not implemented", &window_attention},
    {"window_partition", "vision", "no family claim", &window_partition},
    {"window_rfft_power_mel_log", "audio", "planned contract; no backend implementation evidence", &window_rfft_power_mel_log},
    {"window_unpartition", "vision", "no family claim", &window_unpartition},
}};

}  // namespace quixicore::xpu::contract_stubs
