#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace quixicore::contract {

enum class OperationId : std::uint16_t {
  accumulate,
  act_quant_int8,
  adamw,
  adamw_masked,
  adaptive_norm_modulation,
  adaptive_norm_modulation_qkv,
  adaptive_rms_norm_modulation,
  adaptive_rms_norm_modulation_qkv,
  add_id,
  add_relative_position_2d,
  add_scalar,
  all_gather_gemm,
  all_reduce_rms_norm,
  arange,
  argmax,
  argsort,
  attention,
  attention_backward,
  attention_gate_residual,
  attention_with_lse,
  audio_causal_depthwise_conv1d,
  audio_conv1d,
  audio_conv1d_direct,
  audio_depthwise_conv1d,
  audio_relative_attention,
  audio_resample,
  avg_pool2d_tokens,
  base_q_dequant,
  base_q_embedding,
  base_q_gemm,
  base_q_gemv,
  base_q_lm_head_argmax,
  base_q_moe_gemm,
  base_q_moe_swiglu,
  base_q_qkv,
  base_q_swiglu,
  based_attention,
  biased_attention,
  broadcast,
  calibration_absmax,
  causal_conv3d_cache_update,
  causal_conv_gate_residual,
  clamp,
  classifier_free_guidance_combine,
  classifier_free_guidance_scheduler_step,
  col2im_1d,
  col2im_2d,
  complex_gemm,
  concat,
  conv2d,
  conv3d,
  conv_transpose_1d,
  conv_transpose_2d,
  conv_transpose_overlap_add,
  cosine,
  count_equal,
  cross_attention,
  cross_entropy,
  cross_entropy_backward,
  ctc_decode,
  cumulative_sum,
  decode_cache_attention,
  decode_linear,
  decode_linear_q8,
  decode_linear_residual,
  decode_swiglu,
  deformable_attention,
  dense_gemm,
  dense_gemm_ex,
  depthwise_conv2d,
  dequant_gather,
  deterministic_noise,
  diag_embed,
  diag_mask,
  diffusion_scheduler_step,
  divide,
  down_projection_residual,
  downsample_3d,
  downsample_conv2d,
  dropout,
  dsv4_hc_comb,
  dsv4_hc_post,
  dsv4_hc_pre,
  edge_mlp_256x7,
  embedding_backward,
  embedding_lookup,
  embedding_lookup_types,
  extract_patches_2d,
  extract_patches_3d,
  factorized_position_2d,
  fake_quant_float8,
  fake_quant_int8,
  fft_convolution,
  fill,
  flow_euler_step,
  flow_step_action_clamp_denormalize,
  fp8_gemm,
  fp8_scaled_gemm,
  gate_up_projection_swiglu,
  gated_linear_attention,
  gdn_gate_beta,
  gdn_gated_rmsnorm,
  gdn_qkv_prepare,
  gdn_recurrence,
  gdn_short_conv,
  geglu_projection,
  gelu,
  gelu_backward,
  gemm_gate_residual,
  get_relative_position,
  gguf_gemv,
  glu,
  grammar_mask,
  grid_sample,
  group_norm,
  group_norm_silu,
  grouped_gemm,
  hadamard,
  hedgehog_attention,
  im2col_2d,
  im2col_3d,
  indexer_k_gather,
  int8_gemm,
  interpolate_position_2d,
  istft,
  joint_multimodal_attention,
  kd_ce_fused_bwd,
  kd_ce_fused_fwd,
  kd_kl_dense_bwd,
  kd_kl_dense_fwd,
  kd_kl_topk_bwd,
  kd_kl_topk_fwd,
  kv_cache_compact,
  kv_cache_copy_blocks_q8_0,
  kv_cache_gather,
  kv_cache_gather_bitnet_kv3,
  kv_cache_gather_q8_0,
  kv_cache_offload,
  kv_cache_scatter,
  kv_cache_scatter_bitnet_kv3,
  kv_cache_scatter_q8_0,
  l2_normalize,
  layer_norm,
  leaky_relu,
  linear_attention,
  linear_attention_unnormalized,
  linear_epilogue,
  lm_head_beam_advance,
  lm_head_candidates,
  lm_head_masked,
  log_mel_spectrogram,
  logarithm,
  logits_bias_penalties_top_k_top_p_sample,
  logits_softcap,
  lora_apply,
  lora_apply_direct_f16,
  lowbit_gemv,
  mamba2_backward,
  masked_mean_pool_rms_l2,
  mean_pool_rms_l2,
  mixed_prefill_decode_attention,
  moe_all_to_all_dispatch,
  moe_finalize_backward,
  moe_gather_backward,
  moe_grouped_gemm_backward_input,
  moe_grouped_gemm_backward_weight,
  moe_grouped_gemm_swiglu,
  moe_grouped_qgemm,
  moe_grouped_qswiglu,
  moe_route_grouped,
  moe_route_top_k_prefix_sum_permute,
  moe_route_topk,
  moe_unpermute_weighted_reduce,
  mrope,
  multi_codebook_sample,
  multimodal_rope_nd,
  multimodal_stream_deinterleave,
  multimodal_stream_interleave,
  multiply,
  multistream_logits_codebook_sample,
  mxfp4_gemv,
  mxfp8_gemm,
  non_max_suppression,
  norm_quant,
  nvfp4_gemm,
  nvfp4_gemv,
  outer_product,
  overlap_add,
  pad_2d,
  pad_reflect_1d,
  paged_attention_advanced,
  paged_attention_bitnet_kv3,
  paged_attention_output_projection_residual,
  paged_attention_q8_0,
  paged_attention_turboquant,
  patch_merge_layer_norm,
  patchify_nd,
  patchify_projection_position,
  pixel_shuffle,
  pool1d,
  pool2d,
  pool2d_backward,
  pool_tokens_by_position,
  prefix_append_attention,
  qgeglu,
  qgemm,
  qgemm_backward_input,
  qgemm_int,
  qgemm_q4q8,
  qgemv,
  qgemv_qkv,
  qgemv_up_gate,
  qgemv_up_gate_activation,
  qk_norm_rope,
  qk_norm_rope_attention,
  qk_norm_rope_positioned,
  qkv_proj_fused,
  qkv_projection_qk_norm_rope_kv_append,
  quantize_int4_group,
  quantized_attention,
  quantized_embedding,
  quantized_embedding_bag,
  quantized_lm_head_sample,
  qwen_vision_rope_2d,
  ragged_pack,
  ragged_unpack,
  reduce_mean,
  reduce_scatter_gemm,
  reduce_sum,
  reduce_sum_all,
  repeat_2d,
  repeat_backward_2d,
  residual_rms_norm_quant,
  residual_vector_quantize_decode,
  residual_vector_quantize_encode,
  resize_bicubic,
  resize_bilinear,
  resize_normalize_layout_quant,
  rms_norm,
  rms_norm_backward,
  rms_norm_residual_next,
  rnnt_beam_step,
  rnnt_joiner,
  roi_align,
  roll_2d,
  rope,
  rope_3d,
  rotary_positioned,
  rvq_distance_argmin_residual_update,
  rwkv_wkv6,
  rwkv_wkv7,
  sample_categorical,
  scale,
  selective_scan,
  set_rows,
  sgd,
  sigmoid_mul,
  sigmoid_mul_backward,
  silu,
  silu_backward,
  sine,
  softmax,
  softmax_backward,
  solve_lower_triangular,
  space_to_depth_norm_linear,
  speculative_verify_accept_compact_kv,
  square,
  square_root,
  ssd_chunked_backward,
  ssd_decode,
  stft,
  streaming_conv1d_state,
  subtract,
  swiglu_oai,
  temporal_upsample_conv3d,
  tensor_copy,
  tensor_set_4d,
  ternary_code_flip_count,
  ternary_pack,
  ternary_stats,
  ternary_unpack,
  threshold_topk_indices,
  timestep_embedding,
  top_k_renorm,
  top_k_sample,
  top_p_renorm,
  tq2_0_pack,
  tq2_0_unpack,
  triangular_fill,
  turboquant,
  unary,
  unpatchify_nd,
  upsample_3d,
  upsample_conv2d,
  upscale_nearest_2d,
  value_clip,
  vision_patch_projection,
  vision_patch_projection_3d,
  vision_rope_2d,
  window_attention,
  window_partition,
  window_rfft_power_mel_log,
  window_unpartition,
};

struct OperationDescriptor {
  OperationId id;
  std::string_view name;
  std::string_view family;
  std::string_view kind;
  std::string_view maturity;
};

inline constexpr std::array<OperationDescriptor, 303> kOperations{{
    {OperationId::accumulate, "accumulate", "utils", "operation", "observed"},
    {OperationId::act_quant_int8, "act_quant_int8", "quantization", "operation", "observed"},
    {OperationId::adamw, "adamw", "optimizers", "operation", "observed"},
    {OperationId::adamw_masked, "adamw_masked", "optimizers", "operation", "observed"},
    {OperationId::adaptive_norm_modulation, "adaptive_norm_modulation", "diffusion", "primitive", "planned"},
    {OperationId::adaptive_norm_modulation_qkv, "adaptive_norm_modulation_qkv", "diffusion", "fused", "planned"},
    {OperationId::adaptive_rms_norm_modulation, "adaptive_rms_norm_modulation", "diffusion", "primitive", "planned"},
    {OperationId::adaptive_rms_norm_modulation_qkv, "adaptive_rms_norm_modulation_qkv", "diffusion", "fused", "planned"},
    {OperationId::add_id, "add_id", "utils", "operation", "observed"},
    {OperationId::add_relative_position_2d, "add_relative_position_2d", "vision", "operation", "observed"},
    {OperationId::add_scalar, "add_scalar", "utils", "operation", "observed"},
    {OperationId::all_gather_gemm, "all_gather_gemm", "collectives", "fused", "planned"},
    {OperationId::all_reduce_rms_norm, "all_reduce_rms_norm", "collectives", "fused", "planned"},
    {OperationId::arange, "arange", "utils", "operation", "observed"},
    {OperationId::argmax, "argmax", "sampling", "operation", "observed"},
    {OperationId::argsort, "argsort", "utils", "operation", "observed"},
    {OperationId::attention, "attention", "attention", "operation", "observed"},
    {OperationId::attention_backward, "attention_backward", "attention", "operation", "observed"},
    {OperationId::attention_gate_residual, "attention_gate_residual", "attention", "fused", "planned"},
    {OperationId::attention_with_lse, "attention_with_lse", "attention", "operation", "observed"},
    {OperationId::audio_causal_depthwise_conv1d, "audio_causal_depthwise_conv1d", "audio", "operation", "observed"},
    {OperationId::audio_conv1d, "audio_conv1d", "audio", "operation", "observed"},
    {OperationId::audio_conv1d_direct, "audio_conv1d_direct", "audio", "operation", "observed"},
    {OperationId::audio_depthwise_conv1d, "audio_depthwise_conv1d", "audio", "operation", "observed"},
    {OperationId::audio_relative_attention, "audio_relative_attention", "audio", "operation", "observed"},
    {OperationId::audio_resample, "audio_resample", "audio", "primitive", "planned"},
    {OperationId::avg_pool2d_tokens, "avg_pool2d_tokens", "vision", "operation", "observed"},
    {OperationId::base_q_dequant, "base_q_dequant", "quantization", "operation", "observed"},
    {OperationId::base_q_embedding, "base_q_embedding", "quantization", "operation", "observed"},
    {OperationId::base_q_gemm, "base_q_gemm", "quantization", "operation", "observed"},
    {OperationId::base_q_gemv, "base_q_gemv", "quantization", "operation", "observed"},
    {OperationId::base_q_lm_head_argmax, "base_q_lm_head_argmax", "quantization", "operation", "observed"},
    {OperationId::base_q_moe_gemm, "base_q_moe_gemm", "quantization", "operation", "observed"},
    {OperationId::base_q_moe_swiglu, "base_q_moe_swiglu", "quantization", "operation", "observed"},
    {OperationId::base_q_qkv, "base_q_qkv", "quantization", "operation", "observed"},
    {OperationId::base_q_swiglu, "base_q_swiglu", "quantization", "operation", "observed"},
    {OperationId::based_attention, "based_attention", "linear_attention", "operation", "observed"},
    {OperationId::biased_attention, "biased_attention", "attention", "operation", "observed"},
    {OperationId::broadcast, "broadcast", "collectives", "operation", "observed"},
    {OperationId::calibration_absmax, "calibration_absmax", "quantization", "operation", "observed"},
    {OperationId::causal_conv3d_cache_update, "causal_conv3d_cache_update", "convolution", "fused", "planned"},
    {OperationId::causal_conv_gate_residual, "causal_conv_gate_residual", "audio", "fused", "planned"},
    {OperationId::clamp, "clamp", "utils", "operation", "observed"},
    {OperationId::classifier_free_guidance_combine, "classifier_free_guidance_combine", "diffusion", "primitive", "planned"},
    {OperationId::classifier_free_guidance_scheduler_step, "classifier_free_guidance_scheduler_step", "diffusion", "fused", "planned"},
    {OperationId::col2im_1d, "col2im_1d", "convolution", "operation", "observed"},
    {OperationId::col2im_2d, "col2im_2d", "convolution", "operation", "observed"},
    {OperationId::complex_gemm, "complex_gemm", "matmul", "operation", "observed"},
    {OperationId::concat, "concat", "utils", "operation", "observed"},
    {OperationId::conv2d, "conv2d", "convolution", "operation", "observed"},
    {OperationId::conv3d, "conv3d", "convolution", "operation", "observed"},
    {OperationId::conv_transpose_1d, "conv_transpose_1d", "convolution", "operation", "observed"},
    {OperationId::conv_transpose_2d, "conv_transpose_2d", "convolution", "operation", "observed"},
    {OperationId::conv_transpose_overlap_add, "conv_transpose_overlap_add", "audio", "fused", "planned"},
    {OperationId::cosine, "cosine", "utils", "operation", "observed"},
    {OperationId::count_equal, "count_equal", "utils", "operation", "observed"},
    {OperationId::cross_attention, "cross_attention", "attention", "operation", "observed"},
    {OperationId::cross_entropy, "cross_entropy", "utils", "operation", "observed"},
    {OperationId::cross_entropy_backward, "cross_entropy_backward", "utils", "operation", "observed"},
    {OperationId::ctc_decode, "ctc_decode", "audio", "primitive", "planned"},
    {OperationId::cumulative_sum, "cumulative_sum", "utils", "operation", "observed"},
    {OperationId::decode_cache_attention, "decode_cache_attention", "attention", "operation", "observed"},
    {OperationId::decode_linear, "decode_linear", "matmul", "operation", "observed"},
    {OperationId::decode_linear_q8, "decode_linear_q8", "matmul", "operation", "observed"},
    {OperationId::decode_linear_residual, "decode_linear_residual", "matmul", "operation", "observed"},
    {OperationId::decode_swiglu, "decode_swiglu", "matmul", "operation", "observed"},
    {OperationId::deformable_attention, "deformable_attention", "vision", "primitive", "planned"},
    {OperationId::dense_gemm, "dense_gemm", "matmul", "operation", "observed"},
    {OperationId::dense_gemm_ex, "dense_gemm_ex", "matmul", "operation", "observed"},
    {OperationId::depthwise_conv2d, "depthwise_conv2d", "convolution", "operation", "observed"},
    {OperationId::dequant_gather, "dequant_gather", "quantization", "operation", "observed"},
    {OperationId::deterministic_noise, "deterministic_noise", "diffusion", "primitive", "planned"},
    {OperationId::diag_embed, "diag_embed", "utils", "operation", "observed"},
    {OperationId::diag_mask, "diag_mask", "utils", "operation", "observed"},
    {OperationId::diffusion_scheduler_step, "diffusion_scheduler_step", "diffusion", "primitive", "planned"},
    {OperationId::divide, "divide", "utils", "operation", "observed"},
    {OperationId::down_projection_residual, "down_projection_residual", "matmul", "fused", "planned"},
    {OperationId::downsample_3d, "downsample_3d", "convolution", "primitive", "planned"},
    {OperationId::downsample_conv2d, "downsample_conv2d", "convolution", "fused", "planned"},
    {OperationId::dropout, "dropout", "utils", "operation", "observed"},
    {OperationId::dsv4_hc_comb, "dsv4_hc_comb", "ssm", "operation", "observed"},
    {OperationId::dsv4_hc_post, "dsv4_hc_post", "ssm", "operation", "observed"},
    {OperationId::dsv4_hc_pre, "dsv4_hc_pre", "ssm", "operation", "observed"},
    {OperationId::edge_mlp_256x7, "edge_mlp_256x7", "vision", "operation", "observed"},
    {OperationId::embedding_backward, "embedding_backward", "serving", "operation", "observed"},
    {OperationId::embedding_lookup, "embedding_lookup", "serving", "operation", "observed"},
    {OperationId::embedding_lookup_types, "embedding_lookup_types", "serving", "operation", "observed"},
    {OperationId::extract_patches_2d, "extract_patches_2d", "vision", "operation", "observed"},
    {OperationId::extract_patches_3d, "extract_patches_3d", "vision", "operation", "observed"},
    {OperationId::factorized_position_2d, "factorized_position_2d", "vision", "operation", "observed"},
    {OperationId::fake_quant_float8, "fake_quant_float8", "quantization", "operation", "observed"},
    {OperationId::fake_quant_int8, "fake_quant_int8", "quantization", "operation", "observed"},
    {OperationId::fft_convolution, "fft_convolution", "ssm", "operation", "observed"},
    {OperationId::fill, "fill", "utils", "operation", "observed"},
    {OperationId::flow_euler_step, "flow_euler_step", "diffusion", "primitive", "planned"},
    {OperationId::flow_step_action_clamp_denormalize, "flow_step_action_clamp_denormalize", "vla_world_models", "fused", "planned"},
    {OperationId::fp8_gemm, "fp8_gemm", "quantization", "operation", "observed"},
    {OperationId::fp8_scaled_gemm, "fp8_scaled_gemm", "matmul", "operation", "observed"},
    {OperationId::gate_up_projection_swiglu, "gate_up_projection_swiglu", "matmul", "fused", "planned"},
    {OperationId::gated_linear_attention, "gated_linear_attention", "linear_attention", "operation", "observed"},
    {OperationId::gdn_gate_beta, "gdn_gate_beta", "linear_attention", "operation", "observed"},
    {OperationId::gdn_gated_rmsnorm, "gdn_gated_rmsnorm", "linear_attention", "operation", "observed"},
    {OperationId::gdn_qkv_prepare, "gdn_qkv_prepare", "linear_attention", "operation", "observed"},
    {OperationId::gdn_recurrence, "gdn_recurrence", "linear_attention", "operation", "observed"},
    {OperationId::gdn_short_conv, "gdn_short_conv", "linear_attention", "operation", "observed"},
    {OperationId::geglu_projection, "geglu_projection", "matmul", "fused", "planned"},
    {OperationId::gelu, "gelu", "activations", "operation", "observed"},
    {OperationId::gelu_backward, "gelu_backward", "activations", "operation", "observed"},
    {OperationId::gemm_gate_residual, "gemm_gate_residual", "matmul", "operation", "observed"},
    {OperationId::get_relative_position, "get_relative_position", "vision", "operation", "observed"},
    {OperationId::gguf_gemv, "gguf_gemv", "quantization", "operation", "observed"},
    {OperationId::glu, "glu", "activations", "operation", "observed"},
    {OperationId::grammar_mask, "grammar_mask", "sampling", "primitive", "planned"},
    {OperationId::grid_sample, "grid_sample", "vision", "primitive", "planned"},
    {OperationId::group_norm, "group_norm", "utils", "operation", "observed"},
    {OperationId::group_norm_silu, "group_norm_silu", "convolution", "fused", "planned"},
    {OperationId::grouped_gemm, "grouped_gemm", "matmul", "operation", "observed"},
    {OperationId::hadamard, "hadamard", "utils", "operation", "observed"},
    {OperationId::hedgehog_attention, "hedgehog_attention", "linear_attention", "operation", "observed"},
    {OperationId::im2col_2d, "im2col_2d", "convolution", "operation", "observed"},
    {OperationId::im2col_3d, "im2col_3d", "convolution", "operation", "observed"},
    {OperationId::indexer_k_gather, "indexer_k_gather", "serving", "operation", "observed"},
    {OperationId::int8_gemm, "int8_gemm", "matmul", "operation", "observed"},
    {OperationId::interpolate_position_2d, "interpolate_position_2d", "vision", "operation", "observed"},
    {OperationId::istft, "istft", "audio", "primitive", "planned"},
    {OperationId::joint_multimodal_attention, "joint_multimodal_attention", "multimodal", "primitive", "planned"},
    {OperationId::kd_ce_fused_bwd, "kd_ce_fused_bwd", "utils", "operation", "observed"},
    {OperationId::kd_ce_fused_fwd, "kd_ce_fused_fwd", "utils", "operation", "observed"},
    {OperationId::kd_kl_dense_bwd, "kd_kl_dense_bwd", "utils", "operation", "observed"},
    {OperationId::kd_kl_dense_fwd, "kd_kl_dense_fwd", "utils", "operation", "observed"},
    {OperationId::kd_kl_topk_bwd, "kd_kl_topk_bwd", "utils", "operation", "observed"},
    {OperationId::kd_kl_topk_fwd, "kd_kl_topk_fwd", "utils", "operation", "observed"},
    {OperationId::kv_cache_compact, "kv_cache_compact", "serving", "primitive", "planned"},
    {OperationId::kv_cache_copy_blocks_q8_0, "kv_cache_copy_blocks_q8_0", "serving", "operation", "observed"},
    {OperationId::kv_cache_gather, "kv_cache_gather", "serving", "operation", "observed"},
    {OperationId::kv_cache_gather_bitnet_kv3, "kv_cache_gather_bitnet_kv3", "serving", "operation", "observed"},
    {OperationId::kv_cache_gather_q8_0, "kv_cache_gather_q8_0", "serving", "operation", "observed"},
    {OperationId::kv_cache_offload, "kv_cache_offload", "serving", "primitive", "planned"},
    {OperationId::kv_cache_scatter, "kv_cache_scatter", "serving", "operation", "observed"},
    {OperationId::kv_cache_scatter_bitnet_kv3, "kv_cache_scatter_bitnet_kv3", "serving", "operation", "observed"},
    {OperationId::kv_cache_scatter_q8_0, "kv_cache_scatter_q8_0", "serving", "operation", "observed"},
    {OperationId::l2_normalize, "l2_normalize", "utils", "operation", "observed"},
    {OperationId::layer_norm, "layer_norm", "norms", "operation", "observed"},
    {OperationId::leaky_relu, "leaky_relu", "activations", "operation", "observed"},
    {OperationId::linear_attention, "linear_attention", "linear_attention", "operation", "observed"},
    {OperationId::linear_attention_unnormalized, "linear_attention_unnormalized", "linear_attention", "operation", "observed"},
    {OperationId::linear_epilogue, "linear_epilogue", "matmul", "operation", "observed"},
    {OperationId::lm_head_beam_advance, "lm_head_beam_advance", "quantization", "operation", "observed"},
    {OperationId::lm_head_candidates, "lm_head_candidates", "quantization", "operation", "observed"},
    {OperationId::lm_head_masked, "lm_head_masked", "quantization", "operation", "observed"},
    {OperationId::log_mel_spectrogram, "log_mel_spectrogram", "audio", "primitive", "planned"},
    {OperationId::logarithm, "logarithm", "utils", "operation", "observed"},
    {OperationId::logits_bias_penalties_top_k_top_p_sample, "logits_bias_penalties_top_k_top_p_sample", "sampling", "fused", "planned"},
    {OperationId::logits_softcap, "logits_softcap", "sampling", "operation", "observed"},
    {OperationId::lora_apply, "lora_apply", "matmul", "operation", "observed"},
    {OperationId::lora_apply_direct_f16, "lora_apply_direct_f16", "matmul", "operation", "observed"},
    {OperationId::lowbit_gemv, "lowbit_gemv", "quantization", "operation", "observed"},
    {OperationId::mamba2_backward, "mamba2_backward", "ssm", "operation", "observed"},
    {OperationId::masked_mean_pool_rms_l2, "masked_mean_pool_rms_l2", "serving", "operation", "observed"},
    {OperationId::mean_pool_rms_l2, "mean_pool_rms_l2", "pooling", "operation", "observed"},
    {OperationId::mixed_prefill_decode_attention, "mixed_prefill_decode_attention", "attention", "primitive", "planned"},
    {OperationId::moe_all_to_all_dispatch, "moe_all_to_all_dispatch", "collectives", "fused", "planned"},
    {OperationId::moe_finalize_backward, "moe_finalize_backward", "moe", "operation", "observed"},
    {OperationId::moe_gather_backward, "moe_gather_backward", "moe", "operation", "observed"},
    {OperationId::moe_grouped_gemm_backward_input, "moe_grouped_gemm_backward_input", "moe", "operation", "observed"},
    {OperationId::moe_grouped_gemm_backward_weight, "moe_grouped_gemm_backward_weight", "moe", "operation", "observed"},
    {OperationId::moe_grouped_gemm_swiglu, "moe_grouped_gemm_swiglu", "moe", "fused", "planned"},
    {OperationId::moe_grouped_qgemm, "moe_grouped_qgemm", "moe", "operation", "observed"},
    {OperationId::moe_grouped_qswiglu, "moe_grouped_qswiglu", "moe", "operation", "observed"},
    {OperationId::moe_route_grouped, "moe_route_grouped", "moe", "operation", "observed"},
    {OperationId::moe_route_top_k_prefix_sum_permute, "moe_route_top_k_prefix_sum_permute", "moe", "fused", "planned"},
    {OperationId::moe_route_topk, "moe_route_topk", "moe", "operation", "observed"},
    {OperationId::moe_unpermute_weighted_reduce, "moe_unpermute_weighted_reduce", "moe", "fused", "planned"},
    {OperationId::mrope, "mrope", "attention", "operation", "observed"},
    {OperationId::multi_codebook_sample, "multi_codebook_sample", "audio", "primitive", "planned"},
    {OperationId::multimodal_rope_nd, "multimodal_rope_nd", "multimodal", "primitive", "planned"},
    {OperationId::multimodal_stream_deinterleave, "multimodal_stream_deinterleave", "multimodal", "primitive", "planned"},
    {OperationId::multimodal_stream_interleave, "multimodal_stream_interleave", "multimodal", "primitive", "planned"},
    {OperationId::multiply, "multiply", "utils", "operation", "observed"},
    {OperationId::multistream_logits_codebook_sample, "multistream_logits_codebook_sample", "audio", "fused", "planned"},
    {OperationId::mxfp4_gemv, "mxfp4_gemv", "quantization", "operation", "observed"},
    {OperationId::mxfp8_gemm, "mxfp8_gemm", "matmul", "operation", "observed"},
    {OperationId::non_max_suppression, "non_max_suppression", "vision", "primitive", "planned"},
    {OperationId::norm_quant, "norm_quant", "norms", "operation", "observed"},
    {OperationId::nvfp4_gemm, "nvfp4_gemm", "matmul", "operation", "observed"},
    {OperationId::nvfp4_gemv, "nvfp4_gemv", "quantization", "operation", "observed"},
    {OperationId::outer_product, "outer_product", "utils", "operation", "observed"},
    {OperationId::overlap_add, "overlap_add", "audio", "primitive", "planned"},
    {OperationId::pad_2d, "pad_2d", "utils", "operation", "observed"},
    {OperationId::pad_reflect_1d, "pad_reflect_1d", "utils", "operation", "observed"},
    {OperationId::paged_attention_advanced, "paged_attention_advanced", "serving", "operation", "observed"},
    {OperationId::paged_attention_bitnet_kv3, "paged_attention_bitnet_kv3", "serving", "operation", "observed"},
    {OperationId::paged_attention_output_projection_residual, "paged_attention_output_projection_residual", "attention", "fused", "planned"},
    {OperationId::paged_attention_q8_0, "paged_attention_q8_0", "attention", "operation", "observed"},
    {OperationId::paged_attention_turboquant, "paged_attention_turboquant", "serving", "operation", "observed"},
    {OperationId::patch_merge_layer_norm, "patch_merge_layer_norm", "vision", "operation", "observed"},
    {OperationId::patchify_nd, "patchify_nd", "diffusion", "primitive", "planned"},
    {OperationId::patchify_projection_position, "patchify_projection_position", "vision", "fused", "planned"},
    {OperationId::pixel_shuffle, "pixel_shuffle", "vision", "primitive", "planned"},
    {OperationId::pool1d, "pool1d", "convolution", "operation", "observed"},
    {OperationId::pool2d, "pool2d", "convolution", "operation", "observed"},
    {OperationId::pool2d_backward, "pool2d_backward", "convolution", "operation", "observed"},
    {OperationId::pool_tokens_by_position, "pool_tokens_by_position", "vision", "operation", "observed"},
    {OperationId::prefix_append_attention, "prefix_append_attention", "attention", "primitive", "planned"},
    {OperationId::qgeglu, "qgeglu", "quantization", "operation", "observed"},
    {OperationId::qgemm, "qgemm", "quantization", "operation", "observed"},
    {OperationId::qgemm_backward_input, "qgemm_backward_input", "quantization", "operation", "observed"},
    {OperationId::qgemm_int, "qgemm_int", "quantization", "operation", "observed"},
    {OperationId::qgemm_q4q8, "qgemm_q4q8", "quantization", "operation", "observed"},
    {OperationId::qgemv, "qgemv", "quantization", "operation", "observed"},
    {OperationId::qgemv_qkv, "qgemv_qkv", "quantization", "operation", "observed"},
    {OperationId::qgemv_up_gate, "qgemv_up_gate", "quantization", "operation", "observed"},
    {OperationId::qgemv_up_gate_activation, "qgemv_up_gate_activation", "quantization", "operation", "observed"},
    {OperationId::qk_norm_rope, "qk_norm_rope", "norms", "operation", "observed"},
    {OperationId::qk_norm_rope_attention, "qk_norm_rope_attention", "attention", "fused", "planned"},
    {OperationId::qk_norm_rope_positioned, "qk_norm_rope_positioned", "norms", "operation", "observed"},
    {OperationId::qkv_proj_fused, "qkv_proj_fused", "quantization", "operation", "observed"},
    {OperationId::qkv_projection_qk_norm_rope_kv_append, "qkv_projection_qk_norm_rope_kv_append", "attention", "fused", "planned"},
    {OperationId::quantize_int4_group, "quantize_int4_group", "quantization", "operation", "observed"},
    {OperationId::quantized_attention, "quantized_attention", "serving", "operation", "observed"},
    {OperationId::quantized_embedding, "quantized_embedding", "quantization", "operation", "observed"},
    {OperationId::quantized_embedding_bag, "quantized_embedding_bag", "quantization", "operation", "observed"},
    {OperationId::quantized_lm_head_sample, "quantized_lm_head_sample", "quantization", "operation", "observed"},
    {OperationId::qwen_vision_rope_2d, "qwen_vision_rope_2d", "vision", "operation", "observed"},
    {OperationId::ragged_pack, "ragged_pack", "multimodal", "primitive", "planned"},
    {OperationId::ragged_unpack, "ragged_unpack", "multimodal", "primitive", "planned"},
    {OperationId::reduce_mean, "reduce_mean", "utils", "operation", "observed"},
    {OperationId::reduce_scatter_gemm, "reduce_scatter_gemm", "collectives", "fused", "planned"},
    {OperationId::reduce_sum, "reduce_sum", "collectives", "operation", "observed"},
    {OperationId::reduce_sum_all, "reduce_sum_all", "utils", "operation", "observed"},
    {OperationId::repeat_2d, "repeat_2d", "utils", "operation", "observed"},
    {OperationId::repeat_backward_2d, "repeat_backward_2d", "utils", "operation", "observed"},
    {OperationId::residual_rms_norm_quant, "residual_rms_norm_quant", "norms", "fused", "planned"},
    {OperationId::residual_vector_quantize_decode, "residual_vector_quantize_decode", "audio", "primitive", "planned"},
    {OperationId::residual_vector_quantize_encode, "residual_vector_quantize_encode", "audio", "primitive", "planned"},
    {OperationId::resize_bicubic, "resize_bicubic", "vision", "primitive", "planned"},
    {OperationId::resize_bilinear, "resize_bilinear", "vision", "primitive", "planned"},
    {OperationId::resize_normalize_layout_quant, "resize_normalize_layout_quant", "vision", "fused", "planned"},
    {OperationId::rms_norm, "rms_norm", "norms", "operation", "observed"},
    {OperationId::rms_norm_backward, "rms_norm_backward", "norms", "operation", "observed"},
    {OperationId::rms_norm_residual_next, "rms_norm_residual_next", "norms", "operation", "observed"},
    {OperationId::rnnt_beam_step, "rnnt_beam_step", "audio", "primitive", "planned"},
    {OperationId::rnnt_joiner, "rnnt_joiner", "audio", "primitive", "planned"},
    {OperationId::roi_align, "roi_align", "vision", "primitive", "planned"},
    {OperationId::roll_2d, "roll_2d", "utils", "operation", "observed"},
    {OperationId::rope, "rope", "attention", "operation", "observed"},
    {OperationId::rope_3d, "rope_3d", "diffusion", "primitive", "planned"},
    {OperationId::rotary_positioned, "rotary_positioned", "attention", "operation", "observed"},
    {OperationId::rvq_distance_argmin_residual_update, "rvq_distance_argmin_residual_update", "audio", "fused", "planned"},
    {OperationId::rwkv_wkv6, "rwkv_wkv6", "linear_attention", "operation", "observed"},
    {OperationId::rwkv_wkv7, "rwkv_wkv7", "linear_attention", "operation", "observed"},
    {OperationId::sample_categorical, "sample_categorical", "sampling", "operation", "observed"},
    {OperationId::scale, "scale", "utils", "operation", "observed"},
    {OperationId::selective_scan, "selective_scan", "ssm", "operation", "observed"},
    {OperationId::set_rows, "set_rows", "utils", "operation", "observed"},
    {OperationId::sgd, "sgd", "optimizers", "operation", "observed"},
    {OperationId::sigmoid_mul, "sigmoid_mul", "activations", "operation", "observed"},
    {OperationId::sigmoid_mul_backward, "sigmoid_mul_backward", "activations", "operation", "observed"},
    {OperationId::silu, "silu", "activations", "operation", "observed"},
    {OperationId::silu_backward, "silu_backward", "activations", "operation", "observed"},
    {OperationId::sine, "sine", "utils", "operation", "observed"},
    {OperationId::softmax, "softmax", "activations", "operation", "observed"},
    {OperationId::softmax_backward, "softmax_backward", "activations", "operation", "observed"},
    {OperationId::solve_lower_triangular, "solve_lower_triangular", "utils", "operation", "observed"},
    {OperationId::space_to_depth_norm_linear, "space_to_depth_norm_linear", "vision", "operation", "observed"},
    {OperationId::speculative_verify_accept_compact_kv, "speculative_verify_accept_compact_kv", "serving", "fused", "planned"},
    {OperationId::square, "square", "utils", "operation", "observed"},
    {OperationId::square_root, "square_root", "utils", "operation", "observed"},
    {OperationId::ssd_chunked_backward, "ssd_chunked_backward", "ssm", "operation", "observed"},
    {OperationId::ssd_decode, "ssd_decode", "ssm", "operation", "observed"},
    {OperationId::stft, "stft", "audio", "primitive", "planned"},
    {OperationId::streaming_conv1d_state, "streaming_conv1d_state", "audio", "primitive", "planned"},
    {OperationId::subtract, "subtract", "utils", "operation", "observed"},
    {OperationId::swiglu_oai, "swiglu_oai", "activations", "operation", "observed"},
    {OperationId::temporal_upsample_conv3d, "temporal_upsample_conv3d", "convolution", "fused", "planned"},
    {OperationId::tensor_copy, "tensor_copy", "utils", "operation", "observed"},
    {OperationId::tensor_set_4d, "tensor_set_4d", "utils", "operation", "observed"},
    {OperationId::ternary_code_flip_count, "ternary_code_flip_count", "quantization", "operation", "observed"},
    {OperationId::ternary_pack, "ternary_pack", "quantization", "operation", "observed"},
    {OperationId::ternary_stats, "ternary_stats", "quantization", "operation", "observed"},
    {OperationId::ternary_unpack, "ternary_unpack", "quantization", "operation", "observed"},
    {OperationId::threshold_topk_indices, "threshold_topk_indices", "utils", "operation", "observed"},
    {OperationId::timestep_embedding, "timestep_embedding", "vision", "operation", "observed"},
    {OperationId::top_k_renorm, "top_k_renorm", "sampling", "operation", "observed"},
    {OperationId::top_k_sample, "top_k_sample", "sampling", "operation", "observed"},
    {OperationId::top_p_renorm, "top_p_renorm", "sampling", "operation", "observed"},
    {OperationId::tq2_0_pack, "tq2_0_pack", "quantization", "operation", "observed"},
    {OperationId::tq2_0_unpack, "tq2_0_unpack", "quantization", "operation", "observed"},
    {OperationId::triangular_fill, "triangular_fill", "utils", "operation", "observed"},
    {OperationId::turboquant, "turboquant", "quantization", "operation", "observed"},
    {OperationId::unary, "unary", "activations", "operation", "observed"},
    {OperationId::unpatchify_nd, "unpatchify_nd", "diffusion", "primitive", "planned"},
    {OperationId::upsample_3d, "upsample_3d", "convolution", "primitive", "planned"},
    {OperationId::upsample_conv2d, "upsample_conv2d", "convolution", "fused", "planned"},
    {OperationId::upscale_nearest_2d, "upscale_nearest_2d", "vision", "operation", "observed"},
    {OperationId::value_clip, "value_clip", "activations", "operation", "observed"},
    {OperationId::vision_patch_projection, "vision_patch_projection", "vision", "operation", "observed"},
    {OperationId::vision_patch_projection_3d, "vision_patch_projection_3d", "vision", "operation", "observed"},
    {OperationId::vision_rope_2d, "vision_rope_2d", "vision", "operation", "observed"},
    {OperationId::window_attention, "window_attention", "attention", "operation", "observed"},
    {OperationId::window_partition, "window_partition", "vision", "operation", "observed"},
    {OperationId::window_rfft_power_mel_log, "window_rfft_power_mel_log", "audio", "fused", "planned"},
    {OperationId::window_unpartition, "window_unpartition", "vision", "operation", "observed"},
}};

[[nodiscard]] constexpr std::string_view operation_name(OperationId id) noexcept {
  for (const auto& operation : kOperations) {
    if (operation.id == id) return operation.name;
  }
  return {};
}

}  // namespace quixicore::contract
